"""Python namespaces generated from the game's bundled ``Constants.xs`` file.

Each uppercase class attribute behaves like its original XS symbol when used in
a string or f-string. Its mapped game value and XS type remain available through
the ``value`` and ``xs_type`` attributes.
"""

from __future__ import annotations

from typing import Final, TypeAlias


XsConstantValue: TypeAlias = int | str


class XsConstant(str):
    """An XS symbol that behaves as its name and retains its mapped game value."""

    value: XsConstantValue | None
    xs_type: str | None

    def __new__(
            cls,
            name: str,
            value: XsConstantValue | None = None,
            xs_type: str | None = None,
    ) -> XsConstant:
        if not name.startswith("c") or not name.isidentifier():
            raise ValueError(f"Invalid XS constant name: {name!r}")
        constant = str.__new__(cls, name)
        constant.value = value
        constant.xs_type = xs_type
        return constant

    @property
    def name(self) -> str:
        """Original symbol used by the XS compiler."""

        return str(self)


class XsConstantAttribute:
    """Constants.xs category: Attributes."""

    FOOD: Final[XsConstant] = XsConstant('cAttributeFood', 0, 'int')
    WOOD: Final[XsConstant] = XsConstant('cAttributeWood', 1, 'int')
    STONE: Final[XsConstant] = XsConstant('cAttributeStone', 2, 'int')
    GOLD: Final[XsConstant] = XsConstant('cAttributeGold', 3, 'int')
    POPULATION_CAP: Final[XsConstant] = XsConstant('cAttributePopulationCap', 4, 'int')
    RELIGION: Final[XsConstant] = XsConstant('cAttributeReligion', 5, 'int')
    CURRENT_AGE: Final[XsConstant] = XsConstant('cAttributeCurrentAge', 6, 'int')
    RELICS: Final[XsConstant] = XsConstant('cAttributeRelics', 7, 'int')
    TRAGE_BONUS: Final[XsConstant] = XsConstant('cAttributeTrageBonus', 8, 'int')
    TRADE_GOODS: Final[XsConstant] = XsConstant('cAttributeTradeGoods', 9, 'int')
    TRADE_PRODUCATION: Final[XsConstant] = XsConstant('cAttributeTradeProducation', 10, 'int')
    POPULATION: Final[XsConstant] = XsConstant('cAttributePopulation', 11, 'int')
    DECAY: Final[XsConstant] = XsConstant('cAttributeDecay', 12, 'int')
    DISCOVERY: Final[XsConstant] = XsConstant('cAttributeDiscovery', 13, 'int')
    RUINS: Final[XsConstant] = XsConstant('cAttributeRuins', 14, 'int')
    MEAT: Final[XsConstant] = XsConstant('cAttributeMeat', 15, 'int')
    BERRIES: Final[XsConstant] = XsConstant('cAttributeBerries', 16, 'int')
    FISH: Final[XsConstant] = XsConstant('cAttributeFish', 17, 'int')
    KILLS: Final[XsConstant] = XsConstant('cAttributeKills', 20, 'int')
    RESEARCH_COUNT: Final[XsConstant] = XsConstant('cAttributeResearchCount', 21, 'int')
    EXPLORATION: Final[XsConstant] = XsConstant('cAttributeExploration', 22, 'int')
    CONVERT_PRIEST: Final[XsConstant] = XsConstant('cAttributeConvertPriest', 27, 'int')
    CONVERT_BUILDING: Final[XsConstant] = XsConstant('cAttributeConvertBuilding', 28, 'int')
    BUILDING_LIMIT: Final[XsConstant] = XsConstant('cAttributeBuildingLimit', 30, 'int')
    FOOD_LIMIT: Final[XsConstant] = XsConstant('cAttributeFoodLimit', 31, 'int')
    UNIT_LIMIT: Final[XsConstant] = XsConstant('cAttributeUnitLimit', 32, 'int')
    EFFECT_FUNCTION_NUMBER: Final[XsConstant] = XsConstant('cAttributeEffectFunctionNumber', 33, 'int')
    FAITH: Final[XsConstant] = XsConstant('cAttributeFaith', 34, 'int')
    FAITH_RECHARGE_RATE: Final[XsConstant] = XsConstant('cAttributeFaithRechargeRate', 35, 'int')
    FARM_FOOD: Final[XsConstant] = XsConstant('cAttributeFarmFood', 36, 'int')
    CIVILIAN_POPULATION: Final[XsConstant] = XsConstant('cAttributeCivilianPopulation', 37, 'int')
    ALL_TECHS_ACHIEVED: Final[XsConstant] = XsConstant('cAttributeAllTechsAchieved', 39, 'int')
    MILITARY_POPULATION: Final[XsConstant] = XsConstant('cAttributeMilitaryPopulation', 40, 'int')
    CONVERSIONS: Final[XsConstant] = XsConstant('cAttributeConversions', 41, 'int')
    WONDER: Final[XsConstant] = XsConstant('cAttributeWonder', 42, 'int')
    RAZINGS: Final[XsConstant] = XsConstant('cAttributeRazings', 43, 'int')
    KILL_RATIO: Final[XsConstant] = XsConstant('cAttributeKillRatio', 44, 'int')
    PLAYER_KILLED: Final[XsConstant] = XsConstant('cAttributePlayerKilled', 45, 'int')
    TRIBUTE_INEFFICENCY: Final[XsConstant] = XsConstant('cAttributeTributeInefficency', 46, 'int')
    GOLD_BONUS: Final[XsConstant] = XsConstant('cAttributeGoldBonus', 47, 'int')
    TOWN_CENTER_UNAVAILABLE: Final[XsConstant] = XsConstant('cAttributeTownCenterUnavailable', 48, 'int')
    GOLD_COUNTER: Final[XsConstant] = XsConstant('cAttributeGoldCounter', 49, 'int')
    WRITING: Final[XsConstant] = XsConstant('cAttributeWriting', 50, 'int')
    MONASTERIES: Final[XsConstant] = XsConstant('cAttributeMonasteries', 52, 'int')
    TRIBUTE: Final[XsConstant] = XsConstant('cAttributeTribute', 53, 'int')
    HOLD_RUINS: Final[XsConstant] = XsConstant('cAttributeHoldRuins', 54, 'int')
    HOLD_RELICS: Final[XsConstant] = XsConstant('cAttributeHoldRelics', 55, 'int')
    ORE: Final[XsConstant] = XsConstant('cAttributeOre', 56, 'int')
    CAPTURED_UNIT: Final[XsConstant] = XsConstant('cAttributeCapturedUnit', 57, 'int')
    TRADE_GOOD_QUALITY: Final[XsConstant] = XsConstant('cAttributeTradeGoodQuality', 59, 'int')
    TRADE_MARKET_LEVEL: Final[XsConstant] = XsConstant('cAttributeTradeMarketLevel', 60, 'int')
    FORMATIONS: Final[XsConstant] = XsConstant('cAttributeFormations', 61, 'int')
    BUILDING_HOUSE_RATE: Final[XsConstant] = XsConstant('cAttributeBuildingHouseRate', 62, 'int')
    GATHER_TAX_RATE: Final[XsConstant] = XsConstant('cAttributeGatherTaxRate', 63, 'int')
    GATHER_ACCUMALATION: Final[XsConstant] = XsConstant('cAttributeGatherAccumalation', 64, 'int')
    SALVAGE_DECAY_RATE: Final[XsConstant] = XsConstant('cAttributeSalvageDecayRate', 65, 'int')
    ALLOW_FORMATIONS: Final[XsConstant] = XsConstant('cAttributeAllowFormations', 66, 'int')
    CAN_CONVERT: Final[XsConstant] = XsConstant('cAttributeCanConvert', 67, 'int')
    SOURCE_MARKET_OR_DOCK_X: Final[XsConstant] = XsConstant('cAttributeSourceMarketOrDockX', 70, 'int')
    SOURCE_MARKET_OR_DOCK_Y: Final[XsConstant] = XsConstant('cAttributeSourceMarketOrDockY', 71, 'int')
    CONVERT_RESISTANCE: Final[XsConstant] = XsConstant('cAttributeConvertResistance', 77, 'int')
    TRADE_VIG_RATE: Final[XsConstant] = XsConstant('cAttributeTradeVigRate', 78, 'int')
    STONE_BONUS: Final[XsConstant] = XsConstant('cAttributeStoneBonus', 79, 'int')
    QUEUED_COUNT: Final[XsConstant] = XsConstant('cAttributeQueuedCount', 80, 'int')
    TRAINING_COUNT: Final[XsConstant] = XsConstant('cAttributeTrainingCount', 81, 'int')
    RAIDER: Final[XsConstant] = XsConstant('cAttributeRaider', 82, 'int')
    BOARDING_RECHARGE_RATE: Final[XsConstant] = XsConstant('cAttributeBoardingRechargeRate', 83, 'int')
    STARTING_VILLAGERS: Final[XsConstant] = XsConstant('cAttributeStartingVillagers', 84, 'int')
    RESEARCH_COST_MOD: Final[XsConstant] = XsConstant('cAttributeResearchCostMod', 85, 'int')
    RESEARCH_TIME_MOD: Final[XsConstant] = XsConstant('cAttributeResearchTimeMod', 86, 'int')
    CONVERT_BOATS: Final[XsConstant] = XsConstant('cAttributeConvertBoats', 87, 'int')
    FISH_TRAP_FOOD: Final[XsConstant] = XsConstant('cAttributeFishTrapFood', 88, 'int')
    HEAL_RATE_MODIFER: Final[XsConstant] = XsConstant('cAttributeHealRateModifer', 89, 'int')
    HEAL_RANGE: Final[XsConstant] = XsConstant('cAttributeHealRange', 90, 'int')
    STARTING_FOOD: Final[XsConstant] = XsConstant('cAttributeStartingFood', 91, 'int')
    STARTING_WOOD: Final[XsConstant] = XsConstant('cAttributeStartingWood', 92, 'int')
    STARTING_STONE: Final[XsConstant] = XsConstant('cAttributeStartingStone', 93, 'int')
    STARTING_GOLD: Final[XsConstant] = XsConstant('cAttributeStartingGold', 94, 'int')
    RAIDER_ABILITY: Final[XsConstant] = XsConstant('cAttributeRaiderAbility', 95, 'int')
    NO_DROPSITE_FARMERS: Final[XsConstant] = XsConstant('cAttributeNoDropsiteFarmers', 96, 'int')
    DOMINANT_SHEEP_CONTROL: Final[XsConstant] = XsConstant('cAttributeDominantSheepControl', 97, 'int')
    OBJECT_COST_SUMMATION: Final[XsConstant] = XsConstant('cAttributeObjectCostSummation', 98, 'int')
    RESEARCH_COST_SUMMATION: Final[XsConstant] = XsConstant('cAttributeResearchCostSummation', 99, 'int')
    RELIC_INCOME_SUMMATION: Final[XsConstant] = XsConstant('cAttributeRelicIncomeSummation', 100, 'int')
    TRADE_INCOME_SUMMATION: Final[XsConstant] = XsConstant('cAttributeTradeIncomeSummation', 101, 'int')
    CASTLE: Final[XsConstant] = XsConstant('cAttributeCastle', 134, 'int')
    HIT_POINT_RAZINGS: Final[XsConstant] = XsConstant('cAttributeHitPointRazings', 135, 'int')
    VALUE_KILLED_BY_OTHERS: Final[XsConstant] = XsConstant('cAttributeValueKilledByOthers', 152, 'int')
    VALUE_RAZED_BY_OTHERS: Final[XsConstant] = XsConstant('cAttributeValueRazedByOthers', 153, 'int')
    KILLED_BY_OTHERS: Final[XsConstant] = XsConstant('cAttributeKilledByOthers', 154, 'int')
    RAZED_BY_OTHERS: Final[XsConstant] = XsConstant('cAttributeRazedByOthers', 155, 'int')
    VALUE_CURRENT_UNITS: Final[XsConstant] = XsConstant('cAttributeValueCurrentUnits', 164, 'int')
    VALUE_CURRENT_BUILDINGS: Final[XsConstant] = XsConstant('cAttributeValueCurrentBuildings', 165, 'int')
    FOOD_TOTAL: Final[XsConstant] = XsConstant('cAttributeFoodTotal', 166, 'int')
    WOOD_TOTAL: Final[XsConstant] = XsConstant('cAttributeWoodTotal', 167, 'int')
    STONE_TOTAL: Final[XsConstant] = XsConstant('cAttributeStoneTotal', 168, 'int')
    GOLD_TOTAL: Final[XsConstant] = XsConstant('cAttributeGoldTotal', 169, 'int')
    TOTAL_VALUE_OF_KILLS: Final[XsConstant] = XsConstant('cAttributeTotalValueOfKills', 170, 'int')
    TOTAL_TRIBUTE_RECEIVED: Final[XsConstant] = XsConstant('cAttributeTotalTributeReceived', 171, 'int')
    TOTAL_VALUE_OF_RAZINGS: Final[XsConstant] = XsConstant('cAttributeTotalValueOfRazings', 172, 'int')
    TOTAL_CASTLES_BUILT: Final[XsConstant] = XsConstant('cAttributeTotalCastlesBuilt', 173, 'int')
    TOTAL_WONDERS_BUILT: Final[XsConstant] = XsConstant('cAttributeTotalWondersBuilt', 174, 'int')
    TRIBUTE_SCORE: Final[XsConstant] = XsConstant('cAttributeTributeScore', 175, 'int')
    CONVERT_MIN_ADJ: Final[XsConstant] = XsConstant('cAttributeConvertMinAdj', 176, 'int')
    CONVERT_MAX_ADJ: Final[XsConstant] = XsConstant('cAttributeConvertMaxAdj', 177, 'int')
    CONVERT_RESIST_MIN_ADJ: Final[XsConstant] = XsConstant('cAttributeConvertResistMinAdj', 178, 'int')
    CONVERT_RESIST_MAX_ADJ: Final[XsConstant] = XsConstant('cAttributeConvertResistMaxAdj', 179, 'int')
    CONVERT_BUILDING_MIN: Final[XsConstant] = XsConstant('cAttributeConvertBuildingMin', 180, 'int')
    CONVERT_BUILDING_MAX: Final[XsConstant] = XsConstant('cAttributeConvertBuildingMax', 181, 'int')
    CONVERT_BUILDING_CHANCE: Final[XsConstant] = XsConstant('cAttributeConvertBuildingChance', 182, 'int')
    SPIES: Final[XsConstant] = XsConstant('cAttributeSpies', 183, 'int')
    VALUE_WONDERS_CASTLES: Final[XsConstant] = XsConstant('cAttributeValueWondersCastles', 184, 'int')
    FOOD_SCORE: Final[XsConstant] = XsConstant('cAttributeFoodScore', 185, 'int')
    WOOD_SCORE: Final[XsConstant] = XsConstant('cAttributeWoodScore', 186, 'int')
    STONE_SCORE: Final[XsConstant] = XsConstant('cAttributeStoneScore', 187, 'int')
    GOLD_SCORE: Final[XsConstant] = XsConstant('cAttributeGoldScore', 188, 'int')
    WOOD_BONUS: Final[XsConstant] = XsConstant('cAttributeWoodBonus', 189, 'int')
    FOOD_BONUS: Final[XsConstant] = XsConstant('cAttributeFoodBonus', 190, 'int')
    RELIC_RATE: Final[XsConstant] = XsConstant('cAttributeRelicRate', 191, 'int')
    HERESY: Final[XsConstant] = XsConstant('cAttributeHeresy', 192, 'int')
    THEOCRACY: Final[XsConstant] = XsConstant('cAttributeTheocracy', 193, 'int')
    CRENELLATIONS: Final[XsConstant] = XsConstant('cAttributeCrenellations', 194, 'int')
    CONSTRUCTION_RATE_MOD: Final[XsConstant] = XsConstant('cAttributeConstructionRateMod', 195, 'int')
    HUN_WONDER_BONUS: Final[XsConstant] = XsConstant('cAttributeHunWonderBonus', 196, 'int')
    SPIES_DISCOUNT: Final[XsConstant] = XsConstant('cAttributeSpiesDiscount', 197, 'int')
    MAP_REVEAL: Final[XsConstant] = XsConstant('cAttributeMapReveal', 203, 'int')
    UNIT_REVEAL: Final[XsConstant] = XsConstant('cAttributeUnitReveal', 204, 'int')
    FEITORIA_FOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeFeitoriaFoodProductivity', 205, 'int')
    FEITORIA_WOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeFeitoriaWoodProductivity', 206, 'int')
    FEITORIA_STONE_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeFeitoriaStoneProductivity', 207, 'int')
    FEITORIA_GOLD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeFeitoriaGoldProductivity', 208, 'int')
    TEMPORARY_MAP_REVEAL: Final[XsConstant] = XsConstant('cAttributeTemporaryMapReveal', 209, 'int')
    REVEAL_INITIAL_TYPE: Final[XsConstant] = XsConstant('cAttributeRevealInitialType', 210, 'int')
    ELEVATION_BONUS_HIGHER: Final[XsConstant] = XsConstant('cAttributeElevationBonusHigher', 211, 'int')
    ELEVATION_BONUS_LOWER: Final[XsConstant] = XsConstant('cAttributeElevationBonusLower', 212, 'int')
    SHEPHERDING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeShepherdingProductivity', 216, 'int')
    FEUDAL_TOWN_CENTER_LIMIT: Final[XsConstant] = XsConstant('cAttributeFeudalTownCenterLimit', 218, 'int')
    FISHING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeFishingProductivity', 219, 'int')
    UNUSED_220: Final[XsConstant] = XsConstant('cAttributeUnused220', 220, 'int')
    MONUMENT_FOOD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeMonumentFoodTrickle', 221, 'int')
    MONUMENT_WOOD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeMonumentWoodTrickle', 222, 'int')
    MONUMENT_STONE_TRICKLE: Final[XsConstant] = XsConstant('cAttributeMonumentStoneTrickle', 223, 'int')
    MONUMENT_GOLD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeMonumentGoldTrickle', 224, 'int')
    RELIC_FOOD_RATE: Final[XsConstant] = XsConstant('cAttributeRelicFoodRate', 225, 'int')
    VILLAGERS_KILLED_BY_GAIA: Final[XsConstant] = XsConstant('cAttributeVillagersKilledByGaia', 226, 'int')
    VILLGAERS_KILLED_BY_ANIMAL: Final[XsConstant] = XsConstant('cAttributeVillgaersKilledByAnimal', 227, 'int')
    VILLAGERS_KILLED_BY_AI_PLAYER: Final[XsConstant] = XsConstant('cAttributeVillagersKilledByAIPlayer', 228, 'int')
    VILLAGERS_KILLED_BY_HUMAN_PLAYER: Final[XsConstant] = XsConstant(
        'cAttributeVillagersKilledByHumanPlayer', 229, 'int',
    )
    FOOD_GENERATION: Final[XsConstant] = XsConstant('cAttributeFoodGeneration', 230, 'int')
    WOOD_GENERATION: Final[XsConstant] = XsConstant('cAttributeWoodGeneration', 231, 'int')
    STONE_GENERATION: Final[XsConstant] = XsConstant('cAttributeStoneGeneration', 232, 'int')
    GOLD_GENERATION: Final[XsConstant] = XsConstant('cAttributeGoldGeneration', 233, 'int')
    SPAWN_CAP: Final[XsConstant] = XsConstant('cAttributeSpawnCap', 234, 'int')
    FLEMISH_MILITIA_POP: Final[XsConstant] = XsConstant('cAttributeFlemishMilitiaPop', 235, 'int')
    GOLD_FARMING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeGoldFarmingProductivity', 236, 'int')
    FOLWARK_COLLECTION_AMOUNT: Final[XsConstant] = XsConstant('cAttributeFolwarkCollectionAmount', 237, 'int')
    FOLWARK_COLLECTION_TYPE: Final[XsConstant] = XsConstant('cAttributeFolwarkCollectionType', 238, 'int')
    BUILDING_ID: Final[XsConstant] = XsConstant('cAttributeBuildingId', 239, 'int')
    UNITS_CONVERTED: Final[XsConstant] = XsConstant('cAttributeUnitsConverted', 240, 'int')
    STONE_GOLD_MINING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeStoneGoldMiningProductivity', 241, 'int')
    WORKSHOP_FOOD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeWorkshopFoodTrickle', 242, 'int')
    WORKSHOP_WOOD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeWorkshopWoodTrickle', 243, 'int')
    WORKSHOP_STONE_TRICKLE: Final[XsConstant] = XsConstant('cAttributeWorkshopStoneTrickle', 244, 'int')
    WORKSHOP_GOLD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeWorkshopGoldTrickle', 245, 'int')
    UNITS_VALUE_TOTAL: Final[XsConstant] = XsConstant('cAttributeUnitsValueTotal', 246, 'int')
    BUILDINGS_VALUE_TOTAL: Final[XsConstant] = XsConstant('cAttributeBuildingsValueTotal', 247, 'int')
    VILLAGERS_CREATED_TOTAL: Final[XsConstant] = XsConstant('cAttributeVillagersCreatedTotal', 248, 'int')
    VILLAGERS_IDLE_PERIODS_TOTAL: Final[XsConstant] = XsConstant('cAttributeVillagersIdlePeriodsTotal', 249, 'int')
    VILLAGERS_IDLE_SECONDS_TOTAL: Final[XsConstant] = XsConstant('cAttributeVillagersIdleSecondsTotal', 250, 'int')
    TRADE_FOOD_PERCENT: Final[XsConstant] = XsConstant('cAttributeTradeFoodPercent', 251, 'int')
    TRADE_WOOD_PERCENT: Final[XsConstant] = XsConstant('cAttributeTradeWoodPercent', 252, 'int')
    TRADE_STONE_PERCENT: Final[XsConstant] = XsConstant('cAttributeTradeStonePercent', 253, 'int')
    LIVESTOCK_FOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeLivestockFoodProductivity', 254, 'int')
    SPEED_UP_BUILDING_TYPE: Final[XsConstant] = XsConstant('cAttributeSpeedUpBuildingType', 255, 'int')
    SPEED_UP_BUILDING_RANGE: Final[XsConstant] = XsConstant('cAttributeSpeedUpBuildingRange', 256, 'int')
    SPEED_UP_PERCENTAGE: Final[XsConstant] = XsConstant('cAttributeSpeedUpPercentage', 257, 'int')
    SPEED_UP_OBJECT_TYPE: Final[XsConstant] = XsConstant('cAttributeSpeedUpObjectType', 258, 'int')
    SPEED_UP_EFFECT_TYPE: Final[XsConstant] = XsConstant('cAttributeSpeedUpEffectType', 259, 'int')
    SPEED_UP_SECONDARY_EFFECT_TYPE: Final[XsConstant] = XsConstant('cAttributeSpeedUpSecondaryEffectType', 260, 'int')
    SPEED_UP_SECONDARY_PERCENTAGE: Final[XsConstant] = XsConstant('cAttributeSpeedUpSecondaryPercentage', 261, 'int')
    CIV_NAME_OVERRIDE: Final[XsConstant] = XsConstant('cAttributeCivNameOverride', 262, 'int')
    STARTING_SCOUT_ID: Final[XsConstant] = XsConstant('cAttributeStartingScoutID', 263, 'int')
    RELIC_WOOD_RATE: Final[XsConstant] = XsConstant('cAttributeRelicWoodRate', 264, 'int')
    RELIC_STONE_RATE: Final[XsConstant] = XsConstant('cAttributeRelicStoneRate', 265, 'int')
    CHOPPING_GOLD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeChoppingGoldProductivity', 266, 'int')
    FORAGING_WOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeForagingWoodProductivity', 267, 'int')
    HUNTING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeHuntingProductivity', 268, 'int')
    TECHNOLOGY_REWARD_EFFECT: Final[XsConstant] = XsConstant('cAttributeTechnologyRewardEffect', 269, 'int')
    UNIT_REPAIR_COST: Final[XsConstant] = XsConstant('cAttributeUnitRepairCost', 270, 'int')
    BUILDING_REPAIR_COST: Final[XsConstant] = XsConstant('cAttributeBuildingRepairCost', 271, 'int')
    ELEVATION_DAMAGE_HIGHER: Final[XsConstant] = XsConstant('cAttributeElevationDamageHigher', 272, 'int')
    ELEVATION_DAMAGE_LOWER: Final[XsConstant] = XsConstant('cAttributeElevationDamageLower', 273, 'int')
    INFANTRY_KILL_REWARD: Final[XsConstant] = XsConstant('cAttributeInfantryKillReward', 274, 'int')
    MILITARY_CAN_CONVERT: Final[XsConstant] = XsConstant('cAttributeMilitaryCanConvert', 279, 'int')
    MILITARY_CONVERSION_RANGE_ADJ: Final[XsConstant] = XsConstant('cAttributeMilitaryConversionRangeAdj', 280, 'int')
    MILITARY_CONVERSION_CHANCE: Final[XsConstant] = XsConstant('cAttributeMilitaryConversionChance', 281, 'int')
    MILITARY_CONVERSION_RECHARGE_RATE: Final[XsConstant] = XsConstant(
        'cAttributeMilitaryConversionRechargeRate', 282, 'int',
    )
    SPAWN_STAY_INSIDE: Final[XsConstant] = XsConstant('cAttributeSpawnStayInside', 283, 'int')
    CAVALRY_KILL_REWARD: Final[XsConstant] = XsConstant('cAttributeCavalryKillReward', 284, 'int')
    TRIGGER_SHARED_VISIBILITY: Final[XsConstant] = XsConstant('cAttributeTriggerSharedVisibility', 285, 'int')
    TRIGGER_SHARED_EXPLORATION: Final[XsConstant] = XsConstant('cAttributeTriggerSharedExploration', 286, 'int')
    MILITARY_FOOD_TRICKLE: Final[XsConstant] = XsConstant('cAttributeMilitaryFoodTrickle', 287, 'int')
    PASTURE_FOOD_AMOUNT: Final[XsConstant] = XsConstant('cAttributePastureFoodAmount', 288, 'int')
    PASTURE_ANIMAL_COUNT: Final[XsConstant] = XsConstant('cAttributePastureAnimalCount', 289, 'int')
    PASTURE_HERDER_COUNT: Final[XsConstant] = XsConstant('cAttributePastureHerderCount', 290, 'int')
    DISABLE_ANIMAL_DECAY: Final[XsConstant] = XsConstant('cAttributeDisableAnimalDecay', 292, 'int')
    HERDING_FOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeHerdingFoodProductivity', 293, 'int')
    SHEPHERDING_FOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeShepherdingFoodProductivity', 294, 'int')
    UNIT_COST_REFUND: Final[XsConstant] = XsConstant('cAttributeUnitCostRefund', 295, 'int')
    FORAGING_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeForagingProductivity', 296, 'int')
    GAIA_KILLS: Final[XsConstant] = XsConstant('cAttributeGaiaKills', 300, 'int')
    PLAYER_1_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer1Kills', 301, 'int')
    PLAYER_2_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer2Kills', 302, 'int')
    PLAYER_3_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer3Kills', 303, 'int')
    PLAYER_4_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer4Kills', 304, 'int')
    PLAYER_5_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer5Kills', 305, 'int')
    PLAYER_6_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer6Kills', 306, 'int')
    PLAYER_7_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer7Kills', 307, 'int')
    PLAYER_8_KILLS: Final[XsConstant] = XsConstant('cAttributePlayer8Kills', 308, 'int')
    KILLS_BY_GAIA: Final[XsConstant] = XsConstant('cAttributeKillsByGaia', 325, 'int')
    KILLS_BY_PLAYER_1: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer1', 326, 'int')
    KILLS_BY_PLAYER_2: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer2', 327, 'int')
    KILLS_BY_PLAYER_3: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer3', 328, 'int')
    KILLS_BY_PLAYER_4: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer4', 329, 'int')
    KILLS_BY_PLAYER_5: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer5', 330, 'int')
    KILLS_BY_PLAYER_6: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer6', 331, 'int')
    KILLS_BY_PLAYER_7: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer7', 332, 'int')
    KILLS_BY_PLAYER_8: Final[XsConstant] = XsConstant('cAttributeKillsByPlayer8', 333, 'int')
    GAIA_RAZINGS: Final[XsConstant] = XsConstant('cAttributeGaiaRazings', 350, 'int')
    PLAYER_1_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer1Razings', 351, 'int')
    PLAYER_2_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer2Razings', 352, 'int')
    PLAYER_3_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer3Razings', 353, 'int')
    PLAYER_4_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer4Razings', 354, 'int')
    PLAYER_5_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer5Razings', 355, 'int')
    PLAYER_6_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer6Razings', 356, 'int')
    PLAYER_7_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer7Razings', 357, 'int')
    PLAYER_8_RAZINGS: Final[XsConstant] = XsConstant('cAttributePlayer8Razings', 358, 'int')
    RAZINGS_BY_GAIA: Final[XsConstant] = XsConstant('cAttributeRazingsByGaia', 375, 'int')
    RAZINGS_BY_PLAYER_1: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer1', 376, 'int')
    RAZINGS_BY_PLAYER_2: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer2', 377, 'int')
    RAZINGS_BY_PLAYER_3: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer3', 378, 'int')
    RAZINGS_BY_PLAYER_4: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer4', 379, 'int')
    RAZINGS_BY_PLAYER_5: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer5', 380, 'int')
    RAZINGS_BY_PLAYER_6: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer6', 381, 'int')
    RAZINGS_BY_PLAYER_7: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer7', 382, 'int')
    RAZINGS_BY_PLAYER_8: Final[XsConstant] = XsConstant('cAttributeRazingsByPlayer8', 383, 'int')
    GAIA_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributeGaiaKillValue', 400, 'int')
    PLAYER_1_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer1KillValue', 401, 'int')
    PLAYER_2_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer2KillValue', 402, 'int')
    PLAYER_3_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer3KillValue', 403, 'int')
    PLAYER_4_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer4KillValue', 404, 'int')
    PLAYER_5_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer5KillValue', 405, 'int')
    PLAYER_6_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer6KillValue', 406, 'int')
    PLAYER_7_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer7KillValue', 407, 'int')
    PLAYER_8_KILL_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer8KillValue', 408, 'int')
    GAIA_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributeGaiaRazingValue', 425, 'int')
    PLAYER_1_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer1RazingValue', 426, 'int')
    PLAYER_2_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer2RazingValue', 427, 'int')
    PLAYER_3_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer3RazingValue', 428, 'int')
    PLAYER_4_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer4RazingValue', 429, 'int')
    PLAYER_5_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer5RazingValue', 430, 'int')
    PLAYER_6_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer6RazingValue', 431, 'int')
    PLAYER_7_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer7RazingValue', 432, 'int')
    PLAYER_8_RAZING_VALUE: Final[XsConstant] = XsConstant('cAttributePlayer8RazingValue', 433, 'int')
    GAIA_TRIBUTE: Final[XsConstant] = XsConstant('cAttributeGaiaTribute', 450, 'int')
    PLAYER_1_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer1Tribute', 451, 'int')
    PLAYER_2_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer2Tribute', 452, 'int')
    PLAYER_3_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer3Tribute', 453, 'int')
    PLAYER_4_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer4Tribute', 454, 'int')
    PLAYER_5_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer5Tribute', 455, 'int')
    PLAYER_6_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer6Tribute', 456, 'int')
    PLAYER_7_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer7Tribute', 457, 'int')
    PLAYER_8_TRIBUTE: Final[XsConstant] = XsConstant('cAttributePlayer8Tribute', 458, 'int')
    TRIBUTE_FROM_GAIA: Final[XsConstant] = XsConstant('cAttributeTributeFromGaia', 475, 'int')
    TRIBUTE_FROM_PLAYER_1: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer1', 476, 'int')
    TRIBUTE_FROM_PLAYER_2: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer2', 477, 'int')
    TRIBUTE_FROM_PLAYER_3: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer3', 478, 'int')
    TRIBUTE_FROM_PLAYER_4: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer4', 479, 'int')
    TRIBUTE_FROM_PLAYER_5: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer5', 480, 'int')
    TRIBUTE_FROM_PLAYER_6: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer6', 481, 'int')
    TRIBUTE_FROM_PLAYER_7: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer7', 482, 'int')
    TRIBUTE_FROM_PLAYER_8: Final[XsConstant] = XsConstant('cAttributeTributeFromPlayer8', 483, 'int')
    CHOPPING_FOOD_PRODUCTIVITY: Final[XsConstant] = XsConstant('cAttributeChoppingFoodProductivity', 502, 'int')


class XsConstantPlayerAge:
    """Constants.xs category: Player Age."""

    DARK_AGE: Final[XsConstant] = XsConstant('cDarkAge', 0, 'int')
    FEUDAL_AGE: Final[XsConstant] = XsConstant('cFeudalAge', 1, 'int')
    CASTLE_AGE: Final[XsConstant] = XsConstant('cCastleAge', 2, 'int')
    IMPERIAL_AGE: Final[XsConstant] = XsConstant('cImperialAge', 3, 'int')
    STONE_AGE: Final[XsConstant] = XsConstant('cStoneAge', 0, 'int')
    TOOL_AGE: Final[XsConstant] = XsConstant('cToolAge', 1, 'int')
    BRONZE_AGE: Final[XsConstant] = XsConstant('cBronzeAge', 2, 'int')
    IRON_AGE: Final[XsConstant] = XsConstant('cIronAge', 3, 'int')


class XsConstantEffectAmount:
    """Constants.xs category: EffectAmount Constants."""

    SET_ATTRIBUTE: Final[XsConstant] = XsConstant('cSetAttribute', 0, 'int')
    MOD_RESOURCE: Final[XsConstant] = XsConstant('cModResource', 1, 'int')
    ENABLE_OBJECT: Final[XsConstant] = XsConstant('cEnableObject', 2, 'int')
    UPGRADE_UNIT: Final[XsConstant] = XsConstant('cUpgradeUnit', 3, 'int')
    ADD_ATTRIBUTE: Final[XsConstant] = XsConstant('cAddAttribute', 4, 'int')
    MUL_ATTRIBUTE: Final[XsConstant] = XsConstant('cMulAttribute', 5, 'int')
    MUL_RESOURCE: Final[XsConstant] = XsConstant('cMulResource', 6, 'int')
    SPAWN_UNIT: Final[XsConstant] = XsConstant('cSpawnUnit', 7, 'int')
    MODIFY_TECH: Final[XsConstant] = XsConstant('cModifyTech', 8, 'int')
    SET_PLAYER_DATA: Final[XsConstant] = XsConstant('cSetPlayerData', 9, 'int')
    SET_UNIT_ATTRIBUTE: Final[XsConstant] = XsConstant('cSetUnitAttribute', 10, 'int')
    ADD_UNIT_ATTRIBUTE: Final[XsConstant] = XsConstant('cAddUnitAttribute', 11, 'int')
    MUL_UNIT_ATTRIBUTE: Final[XsConstant] = XsConstant('cMulUnitAttribute', 12, 'int')
    SET_TECH_COST: Final[XsConstant] = XsConstant('cSetTechCost', 100, 'int')
    ADD_TECH_COST: Final[XsConstant] = XsConstant('cAddTechCost', 101, 'int')
    DISABLE_TECH: Final[XsConstant] = XsConstant('cDisableTech', 102, 'int')
    MOD_TECH_TIME: Final[XsConstant] = XsConstant('cModTechTime', 103, 'int')
    GAIA_SET_ATTRIBUTE: Final[XsConstant] = XsConstant('cGaiaSetAttribute', -1, 'int')
    GAIA_MOD_RESOURCE: Final[XsConstant] = XsConstant('cGaiaModResource', -2, 'int')
    GAIA_ENABLE_OBJECT: Final[XsConstant] = XsConstant('cGaiaEnableObject', -3, 'int')
    GAIA_UPGRADE_UNIT: Final[XsConstant] = XsConstant('cGaiaUpgradeUnit', -4, 'int')
    GAIA_ADD_ATTRIBUTE: Final[XsConstant] = XsConstant('cGaiaAddAttribute', -5, 'int')
    GAIA_MUL_ATTRIBUTE: Final[XsConstant] = XsConstant('cGaiaMulAttribute', -6, 'int')
    GAIA_MUL_RESOURCE: Final[XsConstant] = XsConstant('cGaiaMulResource', -7, 'int')
    GAIA_SPAWN_UNIT: Final[XsConstant] = XsConstant('cGaiaSpawnUnit', -8, 'int')
    GAIA_MODIFY_TECH: Final[XsConstant] = XsConstant('cGaiaModifyTech', -9, 'int')
    GAIA_SET_PLAYER_DATA: Final[XsConstant] = XsConstant('cGaiaSetPlayerData', -10, 'int')
    GAIA_SET_TECH_COST: Final[XsConstant] = XsConstant('cGaiaSetTechCost', -101, 'int')
    GAIA_ADD_TECH_COST: Final[XsConstant] = XsConstant('cGaiaAddTechCost', -102, 'int')
    GAIA_DISABLE_TECH: Final[XsConstant] = XsConstant('cGaiaDisableTech', -103, 'int')
    GAIA_MOD_TECH_TIME: Final[XsConstant] = XsConstant('cGaiaModTechTime', -104, 'int')
    ATTRIBUTE_DISABLE: Final[XsConstant] = XsConstant('cAttributeDisable', 0, 'int')
    ATTRIBUTE_ENABLE: Final[XsConstant] = XsConstant('cAttributeEnable', 1, 'int')
    ATTRIBUTE_FORCE: Final[XsConstant] = XsConstant('cAttributeForce', 2, 'int')
    ATTRIBUTE_RESEARCH: Final[XsConstant] = XsConstant('cAttributeResearch', 3, 'int')
    ATTRIBUTE_SET: Final[XsConstant] = XsConstant('cAttributeSet', 0, 'int')
    ATTRIBUTE_ADD: Final[XsConstant] = XsConstant('cAttributeAdd', 1, 'int')
    ATTR_SET_TIME: Final[XsConstant] = XsConstant('cAttrSetTime', -1, 'int')
    ATTR_ADD_TIME: Final[XsConstant] = XsConstant('cAttrAddTime', -2, 'int')
    ATTR_MUL_TIME: Final[XsConstant] = XsConstant('cAttrMulTime', -3, 'int')
    ATTR_SET_FOOD_COST: Final[XsConstant] = XsConstant('cAttrSetFoodCost', 0, 'int')
    ATTR_SET_WOOD_COST: Final[XsConstant] = XsConstant('cAttrSetWoodCost', 1, 'int')
    ATTR_SET_STONE_COST: Final[XsConstant] = XsConstant('cAttrSetStoneCost', 2, 'int')
    ATTR_SET_GOLD_COST: Final[XsConstant] = XsConstant('cAttrSetGoldCost', 3, 'int')
    ATTR_SET_LOCATION: Final[XsConstant] = XsConstant('cAttrSetLocation', 4, 'int')
    ATTR_SET_BUTTON: Final[XsConstant] = XsConstant('cAttrSetButton', 5, 'int')
    ATTR_SET_ICON: Final[XsConstant] = XsConstant('cAttrSetIcon', 6, 'int')
    ATTR_SET_NAME: Final[XsConstant] = XsConstant('cAttrSetName', 7, 'int')
    ATTR_SET_DESCRIPTION: Final[XsConstant] = XsConstant('cAttrSetDescription', 8, 'int')
    ATTR_SET_STACKING: Final[XsConstant] = XsConstant('cAttrSetStacking', 9, 'int')
    ATTR_SET_STACKING_RESEARCH_CAP: Final[XsConstant] = XsConstant('cAttrSetStackingResearchCap', 10, 'int')
    ATTR_SET_HOTKEY: Final[XsConstant] = XsConstant('cAttrSetHotkey', 11, 'int')
    ATTR_SET_STATE: Final[XsConstant] = XsConstant('cAttrSetState', 12, 'int')
    ATTR_MUL_FOOD_COST: Final[XsConstant] = XsConstant('cAttrMulFoodCost', 13, 'int')
    ATTR_MUL_WOOD_COST: Final[XsConstant] = XsConstant('cAttrMulWoodCost', 14, 'int')
    ATTR_MUL_STONE_COST: Final[XsConstant] = XsConstant('cAttrMulStoneCost', 15, 'int')
    ATTR_MUL_GOLD_COST: Final[XsConstant] = XsConstant('cAttrMulGoldCost', 16, 'int')
    ATTR_MUL_ALL_COSTS: Final[XsConstant] = XsConstant('cAttrMulAllCosts', 17, 'int')
    ATTR_SET_EFFECT: Final[XsConstant] = XsConstant('cAttrSetEffect', 18, 'int')
    ATTR_ADD_FOOD_COST: Final[XsConstant] = XsConstant('cAttrAddFoodCost', 16384, 'int')
    ATTR_ADD_WOOD_COST: Final[XsConstant] = XsConstant('cAttrAddWoodCost', 16385, 'int')
    ATTR_ADD_STONE_COST: Final[XsConstant] = XsConstant('cAttrAddStoneCost', 16386, 'int')
    ATTR_ADD_GOLD_COST: Final[XsConstant] = XsConstant('cAttrAddGoldCost', 16387, 'int')
    HITPOINTS: Final[XsConstant] = XsConstant('cHitpoints', 0, 'int')
    LINE_OF_SIGHT: Final[XsConstant] = XsConstant('cLineOfSight', 1, 'int')
    GARRISON_CAPACITY: Final[XsConstant] = XsConstant('cGarrisonCapacity', 2, 'int')
    UNIT_SIZE_X: Final[XsConstant] = XsConstant('cUnitSizeX', 3, 'int')
    UNIT_SIZE_Y: Final[XsConstant] = XsConstant('cUnitSizeY', 4, 'int')
    MOVEMENT_SPEED: Final[XsConstant] = XsConstant('cMovementSpeed', 5, 'int')
    ROTATION_SPEED: Final[XsConstant] = XsConstant('cRotationSpeed', 6, 'int')
    ARMOR: Final[XsConstant] = XsConstant('cArmor', 8, 'int')
    ATTACK: Final[XsConstant] = XsConstant('cAttack', 9, 'int')
    ATTACK_RELOAD_TIME: Final[XsConstant] = XsConstant('cAttackReloadTime', 10, 'int')
    ACCURACY_PERCENT: Final[XsConstant] = XsConstant('cAccuracyPercent', 11, 'int')
    MAX_RANGE: Final[XsConstant] = XsConstant('cMaxRange', 12, 'int')
    WORK_RATE: Final[XsConstant] = XsConstant('cWorkRate', 13, 'int')
    CARRY_CAPACITY: Final[XsConstant] = XsConstant('cCarryCapacity', 14, 'int')
    BASE_ARMOR: Final[XsConstant] = XsConstant('cBaseArmor', 15, 'int')
    PROJECTILE_UNIT: Final[XsConstant] = XsConstant('cProjectileUnit', 16, 'int')
    ICON_GRAPHICS_ANGLE: Final[XsConstant] = XsConstant('cIconGraphicsAngle', 17, 'int')
    TERRAIN_DEFENSE_BONUS: Final[XsConstant] = XsConstant('cTerrainDefenseBonus', 18, 'int')
    ENABLE_SMART_PROJECTILE: Final[XsConstant] = XsConstant('cEnableSmartProjectile', 19, 'int')
    MINIMUM_RANGE: Final[XsConstant] = XsConstant('cMinimumRange', 20, 'int')
    AMOUNT_FIRST_STORAGE: Final[XsConstant] = XsConstant('cAmountFirstStorage', 21, 'int')
    BLAST_WIDTH: Final[XsConstant] = XsConstant('cBlastWidth', 22, 'int')
    SEARCH_RADIUS: Final[XsConstant] = XsConstant('cSearchRadius', 23, 'int')
    BONUS_RESISTANCE: Final[XsConstant] = XsConstant('cBonusResistance', 24, 'int')
    ICON_ID: Final[XsConstant] = XsConstant('cIconId', 25, 'int')
    AMOUNT_SECOND_STORAGE: Final[XsConstant] = XsConstant('cAmountSecondStorage', 26, 'int')
    AMOUNT_THIRD_STORAGE: Final[XsConstant] = XsConstant('cAmountThirdStorage', 27, 'int')
    FOG_FLAG: Final[XsConstant] = XsConstant('cFogFlag', 28, 'int')
    OCCLUSION_MODE: Final[XsConstant] = XsConstant('cOcclusionMode', 29, 'int')
    GARRISON_TYPE: Final[XsConstant] = XsConstant('cGarrisonType', 30, 'int')
    UNIT_SIZE_Z: Final[XsConstant] = XsConstant('cUnitSizeZ', 32, 'int')
    CAN_BE_BUILT_ON: Final[XsConstant] = XsConstant('cCanBeBuiltOn', 33, 'int')
    FOUNDATION_TERRAIN: Final[XsConstant] = XsConstant('cFoundationTerrain', 34, 'int')
    HERO_STATUS: Final[XsConstant] = XsConstant('cHeroStatus', 40, 'int')
    ATTACK_DELAY: Final[XsConstant] = XsConstant('cAttackDelay', 41, 'int')
    TRAIN_LOCATION: Final[XsConstant] = XsConstant('cTrainLocation', 42, 'int')
    TRAIN_BUTTON: Final[XsConstant] = XsConstant('cTrainButton', 43, 'int')
    BLAST_ATTACK_LEVEL: Final[XsConstant] = XsConstant('cBlastAttackLevel', 44, 'int')
    BLAST_DEFENSE_LEVEL: Final[XsConstant] = XsConstant('cBlastDefenseLevel', 45, 'int')
    SHOWN_ATTACK: Final[XsConstant] = XsConstant('cShownAttack', 46, 'int')
    SHOWN_RANGE: Final[XsConstant] = XsConstant('cShownRange', 47, 'int')
    SHOWN_MELEE_ARMOR: Final[XsConstant] = XsConstant('cShownMeleeArmor', 48, 'int')
    SHOWN_PIERCE_ARMOR: Final[XsConstant] = XsConstant('cShownPierceArmor', 49, 'int')
    NAME_ID: Final[XsConstant] = XsConstant('cNameId', 50, 'int')
    DESCRIPTION_ID: Final[XsConstant] = XsConstant('cDescriptionId', 51, 'int')
    TERRAIN_TABLE: Final[XsConstant] = XsConstant('cTerrainTable', 53, 'int')
    TRAITS: Final[XsConstant] = XsConstant('cTraits', 54, 'int')
    TRAIT_PIECE: Final[XsConstant] = XsConstant('cTraitPiece', 56, 'int')
    DEAD_UNIT_ID: Final[XsConstant] = XsConstant('cDeadUnitId', 57, 'int')
    HOTKEY_ID: Final[XsConstant] = XsConstant('cHotkeyId', 58, 'int')
    MAX_CHARGE: Final[XsConstant] = XsConstant('cMaxCharge', 59, 'int')
    RECHARGE_RATE: Final[XsConstant] = XsConstant('cRechargeRate', 60, 'int')
    CHARGE_EVENT: Final[XsConstant] = XsConstant('cChargeEvent', 61, 'int')
    CHARGE_TYPE: Final[XsConstant] = XsConstant('cChargeType', 62, 'int')
    COMBAT_ABILITY: Final[XsConstant] = XsConstant('cCombatAbility', 63, 'int')
    ATTACK_DISPERSION: Final[XsConstant] = XsConstant('cAttackDispersion', 64, 'int')
    SECONDARY_PROJECTILE_UNIT: Final[XsConstant] = XsConstant('cSecondaryProjectileUnit', 65, 'int')
    BLOOD_UNIT_ID: Final[XsConstant] = XsConstant('cBloodUnitId', 66, 'int')
    HIT_MODE: Final[XsConstant] = XsConstant('cHitMode', 67, 'int')
    VANISH_MODE: Final[XsConstant] = XsConstant('cVanishMode', 68, 'int')
    PROJECTILE_ARC: Final[XsConstant] = XsConstant('cProjectileArc', 69, 'int')
    ATTACK_GRAPHIC: Final[XsConstant] = XsConstant('cAttackGraphic', 70, 'int')
    STANDING_GRAPHIC: Final[XsConstant] = XsConstant('cStandingGraphic', 71, 'int')
    STANDING_2_GRAPHIC: Final[XsConstant] = XsConstant('cStanding2Graphic', 72, 'int')
    DYING_GRAPHIC: Final[XsConstant] = XsConstant('cDyingGraphic', 73, 'int')
    UNDEAD_GRAPHIC: Final[XsConstant] = XsConstant('cUndeadGraphic', 74, 'int')
    WALKING_GRAPHIC: Final[XsConstant] = XsConstant('cWalkingGraphic', 75, 'int')
    RUNNING_GRAPHIC: Final[XsConstant] = XsConstant('cRunningGraphic', 76, 'int')
    SPECIAL_GRAPHIC: Final[XsConstant] = XsConstant('cSpecialGraphic', 77, 'int')
    OBSTRUCTION_TYPE: Final[XsConstant] = XsConstant('cObstructionType', 78, 'int')
    BLOCKAGE_CLASS: Final[XsConstant] = XsConstant('cBlockageClass', 79, 'int')
    SELECTION_EFFECT: Final[XsConstant] = XsConstant('cSelectionEffect', 80, 'int')
    SPECIAL_ABILITY: Final[XsConstant] = XsConstant('cSpecialAbility', 81, 'int')
    IDLE_ATTACK_GRAPHIC: Final[XsConstant] = XsConstant('cIdleAttackGraphic', 82, 'int')
    HERO_GLOW_GRAPHIC: Final[XsConstant] = XsConstant('cHeroGlowGraphic', 83, 'int')
    GARRISON_GRAPHIC: Final[XsConstant] = XsConstant('cGarrisonGraphic', 84, 'int')
    CONSTRUCTION_GRAPHIC: Final[XsConstant] = XsConstant('cConstructionGraphic', 85, 'int')
    SNOW_GRAPHIC: Final[XsConstant] = XsConstant('cSnowGraphic', 86, 'int')
    DESTRUCTION_GRAPHIC: Final[XsConstant] = XsConstant('cDestructionGraphic', 87, 'int')
    DESTRUCTION_RUBBLE_GRAPHIC: Final[XsConstant] = XsConstant('cDestructionRubbleGraphic', 88, 'int')
    RESEARCHING_GRAPHIC: Final[XsConstant] = XsConstant('cResearchingGraphic', 89, 'int')
    RESEARCH_COMPLETED_GRAPHIC: Final[XsConstant] = XsConstant('cResearchCompletedGraphic', 90, 'int')
    DAMAGE_GRAPHIC: Final[XsConstant] = XsConstant('cDamageGraphic', 91, 'int')
    SELECTION_SOUND: Final[XsConstant] = XsConstant('cSelectionSound', 92, 'int')
    SELECTION_SOUND_EVENT: Final[XsConstant] = XsConstant('cSelectionSoundEvent', 93, 'int')
    DYING_SOUND: Final[XsConstant] = XsConstant('cDyingSound', 94, 'int')
    DYING_SOUND_EVENT: Final[XsConstant] = XsConstant('cDyingSoundEvent', 95, 'int')
    TRAIN_SOUND: Final[XsConstant] = XsConstant('cTrainSound', 96, 'int')
    TRAIN_SOUND_EVENT: Final[XsConstant] = XsConstant('cTrainSoundEvent', 97, 'int')
    DAMAGE_SOUND: Final[XsConstant] = XsConstant('cDamageSound', 98, 'int')
    DAMAGE_SOUND_EVENT: Final[XsConstant] = XsConstant('cDamageSoundEvent', 99, 'int')
    RESOURCE_COST: Final[XsConstant] = XsConstant('cResourceCost', 100, 'int')
    TRAIN_TIME: Final[XsConstant] = XsConstant('cTrainTime', 101, 'int')
    TOTAL_PROJECTILES: Final[XsConstant] = XsConstant('cTotalProjectiles', 102, 'int')
    FOOD_COST: Final[XsConstant] = XsConstant('cFoodCost', 103, 'int')
    WOOD_COST: Final[XsConstant] = XsConstant('cWoodCost', 104, 'int')
    GOLD_COST: Final[XsConstant] = XsConstant('cGoldCost', 105, 'int')
    STONE_COST: Final[XsConstant] = XsConstant('cStoneCost', 106, 'int')
    MAX_TOTAL_PROJECTILES: Final[XsConstant] = XsConstant('cMaxTotalProjectiles', 107, 'int')
    GARRISON_HEAL_RATE: Final[XsConstant] = XsConstant('cGarrisonHealRate', 108, 'int')
    REGENERATION_RATE: Final[XsConstant] = XsConstant('cRegenerationRate', 109, 'int')
    POPULATION: Final[XsConstant] = XsConstant('cPopulation', 110, 'int')
    MIN_CONVERSION_TIME_MOD: Final[XsConstant] = XsConstant('cMinConversionTimeMod', 111, 'int')
    MAX_CONVERSION_TIME_MOD: Final[XsConstant] = XsConstant('cMaxConversionTimeMod', 112, 'int')
    CONVERSION_CHANCE_MOD: Final[XsConstant] = XsConstant('cConversionChanceMod', 113, 'int')
    FORMATION_CATEGORY: Final[XsConstant] = XsConstant('cFormationCategory', 114, 'int')
    AREA_DAMAGE: Final[XsConstant] = XsConstant('cAreaDamage', 115, 'int')
    DAMAGE_REFLECTION: Final[XsConstant] = XsConstant('cDamageReflection', 118, 'int')
    FRIENDLY_FIRE_DAMAGE: Final[XsConstant] = XsConstant('cFriendlyFireDamage', 119, 'int')
    REGENERATION_HP_PERCENT: Final[XsConstant] = XsConstant('cRegenerationHpPercent', 120, 'int')
    BUTTON_ICON_ID: Final[XsConstant] = XsConstant('cButtonIconId', 121, 'int')
    SHORT_TOOLTIP_ID: Final[XsConstant] = XsConstant('cShortTooltipId', 122, 'int')
    EXTENDED_TOOLTIP_ID: Final[XsConstant] = XsConstant('cExtendedTooltipId', 123, 'int')
    HOTKEY_ACTION: Final[XsConstant] = XsConstant('cHotkeyAction', 124, 'int')
    CHARGE_PROJECTILE_UNIT: Final[XsConstant] = XsConstant('cChargeProjectileUnit', 125, 'int')
    AVAILABLE_FLAG: Final[XsConstant] = XsConstant('cAvailableFlag', 126, 'int')
    DISABLED_FLAG: Final[XsConstant] = XsConstant('cDisabledFlag', 127, 'int')
    ATTACK_PRIORITY: Final[XsConstant] = XsConstant('cAttackPriority', 128, 'int')
    INVULNERABILITY_LEVEL: Final[XsConstant] = XsConstant('cInvulnerabilityLevel', 129, 'int')
    GARRISON_FIREPOWER: Final[XsConstant] = XsConstant('cGarrisonFirepower', 130, 'int')
    ATTACK_2_GRAPHIC: Final[XsConstant] = XsConstant('cAttack2Graphic', 131, 'int')
    COMMAND_SOUND: Final[XsConstant] = XsConstant('cCommandSound', 132, 'int')
    COMMAND_SOUND_EVENT: Final[XsConstant] = XsConstant('cCommandSoundEvent', 133, 'int')
    MOVE_SOUND: Final[XsConstant] = XsConstant('cMoveSound', 134, 'int')
    MOVE_SOUND_EVENT: Final[XsConstant] = XsConstant('cMoveSoundEvent', 135, 'int')
    CONSTRUCTION_SOUND: Final[XsConstant] = XsConstant('cConstructionSound', 136, 'int')
    CONSTRUCTION_SOUND_EVENT: Final[XsConstant] = XsConstant('cConstructionSoundEvent', 137, 'int')
    TRANSFORM_SOUND: Final[XsConstant] = XsConstant('cTransformSound', 138, 'int')
    TRANSFORM_SOUND_EVENT: Final[XsConstant] = XsConstant('cTransformSoundEvent', 139, 'int')
    RUN_PATTERN: Final[XsConstant] = XsConstant('cRunPattern', 140, 'int')
    INTERFACE_KIND: Final[XsConstant] = XsConstant('cInterfaceKind', 141, 'int')
    COMBAT_LEVEL: Final[XsConstant] = XsConstant('cCombatLevel', 142, 'int')
    INTERACTION_MODE: Final[XsConstant] = XsConstant('cInteractionMode', 143, 'int')
    MINIMAP_MODE: Final[XsConstant] = XsConstant('cMinimapMode', 144, 'int')
    TRAILING_UNIT: Final[XsConstant] = XsConstant('cTrailingUnit', 145, 'int')
    TRAIL_MODE: Final[XsConstant] = XsConstant('cTrailMode', 146, 'int')
    TRAIL_DENSITY: Final[XsConstant] = XsConstant('cTrailDensity', 147, 'int')
    PROJECTILE_GRAPHIC_DISPLACEMENT_X: Final[XsConstant] = XsConstant('cProjectileGraphicDisplacementX', 148, 'int')
    PROJECTILE_GRAPHIC_DISPLACEMENT_Y: Final[XsConstant] = XsConstant('cProjectileGraphicDisplacementY', 149, 'int')
    PROJECTILE_GRAPHIC_DISPLACEMENT_Z: Final[XsConstant] = XsConstant('cProjectileGraphicDisplacementZ', 150, 'int')
    PROJECTILE_SPAWNING_AREA_WIDTH: Final[XsConstant] = XsConstant('cProjectileSpawningAreaWidth', 151, 'int')
    PROJECTILE_SPAWNING_AREA_LENGTH: Final[XsConstant] = XsConstant('cProjectileSpawningAreaLength', 152, 'int')
    PROJECTILE_SPAWNING_AREA_RANDOMNESS: Final[XsConstant] = XsConstant(
        'cProjectileSpawningAreaRandomness', 153, 'int',
    )
    DAMAGE_GRAPHICS_ENTRY_MOD: Final[XsConstant] = XsConstant('cDamageGraphicsEntryMod', 154, 'int')
    DAMAGE_GRAPHICS_TOTAL_NUM: Final[XsConstant] = XsConstant('cDamageGraphicsTotalNum', 155, 'int')
    DAMAGE_GRAPHIC_PERCENT: Final[XsConstant] = XsConstant('cDamageGraphicPercent', 156, 'int')
    DAMAGE_GRAPHIC_APPLY_MODE: Final[XsConstant] = XsConstant('cDamageGraphicApplyMode', 157, 'int')
    TRAIN_LOCATIONS_ENTRY_MOD: Final[XsConstant] = XsConstant('cTrainLocationsEntryMod', 158, 'int')
    TRAIN_LOCATIONS_TOTAL_NUM: Final[XsConstant] = XsConstant('cTrainLocationsTotalNum', 159, 'int')
    ADD_ARMOR_TYPE: Final[XsConstant] = XsConstant('cAddArmorType', 160, 'int')
    ADD_ATTACK_TYPE: Final[XsConstant] = XsConstant('cAddAttackType', 161, 'int')
    CHARGE_TARGET: Final[XsConstant] = XsConstant('cChargeTarget', 162, 'int')
    SIZE_CLASS: Final[XsConstant] = XsConstant('cSizeClass', 163, 'int')
    REMOVE_ARMOR_TYPE: Final[XsConstant] = XsConstant('cRemoveArmorType', 164, 'int')
    REMOVE_ATTACK_TYPE: Final[XsConstant] = XsConstant('cRemoveAttackType', 165, 'int')


class XsConstantCivilization:
    """Constants.xs category: Player Civilization Constants (default datasets)."""

    GAIA: Final[XsConstant] = XsConstant('cGaia', 0, 'int')
    BRITONS: Final[XsConstant] = XsConstant('cBritons', 1, 'int')
    FRANKS: Final[XsConstant] = XsConstant('cFranks', 2, 'int')
    GOTHS: Final[XsConstant] = XsConstant('cGoths', 3, 'int')
    TEUTONS: Final[XsConstant] = XsConstant('cTeutons', 4, 'int')
    JAPANESE: Final[XsConstant] = XsConstant('cJapanese', 5, 'int')
    CHINESE: Final[XsConstant] = XsConstant('cChinese', 6, 'int')
    BYZANTINES: Final[XsConstant] = XsConstant('cByzantines', 7, 'int')
    PERSIANS: Final[XsConstant] = XsConstant('cPersians', 8, 'int')
    SARACENS: Final[XsConstant] = XsConstant('cSaracens', 9, 'int')
    TURKS: Final[XsConstant] = XsConstant('cTurks', 10, 'int')
    VIKINGS: Final[XsConstant] = XsConstant('cVikings', 11, 'int')
    MONGOLS: Final[XsConstant] = XsConstant('cMongols', 12, 'int')
    CELTS: Final[XsConstant] = XsConstant('cCelts', 13, 'int')
    SPANISH: Final[XsConstant] = XsConstant('cSpanish', 14, 'int')
    AZTECS: Final[XsConstant] = XsConstant('cAztecs', 15, 'int')
    MAYANS: Final[XsConstant] = XsConstant('cMayans', 16, 'int')
    HUNS: Final[XsConstant] = XsConstant('cHuns', 17, 'int')
    KOREANS: Final[XsConstant] = XsConstant('cKoreans', 18, 'int')
    ITALIANS: Final[XsConstant] = XsConstant('cItalians', 19, 'int')
    INDIANS: Final[XsConstant] = XsConstant('cIndians', 20, 'int')
    INCAS: Final[XsConstant] = XsConstant('cIncas', 21, 'int')
    MAGYARS: Final[XsConstant] = XsConstant('cMagyars', 22, 'int')
    SLAVS: Final[XsConstant] = XsConstant('cSlavs', 23, 'int')
    PORTUGUESE: Final[XsConstant] = XsConstant('cPortuguese', 24, 'int')
    ETHIOPIANS: Final[XsConstant] = XsConstant('cEthiopians', 25, 'int')
    MALIANS: Final[XsConstant] = XsConstant('cMalians', 26, 'int')
    BERBERS: Final[XsConstant] = XsConstant('cBerbers', 27, 'int')
    KHMER: Final[XsConstant] = XsConstant('cKhmer', 28, 'int')
    MALAY: Final[XsConstant] = XsConstant('cMalay', 29, 'int')
    BURMESE: Final[XsConstant] = XsConstant('cBurmese', 30, 'int')
    VIETNAMESE: Final[XsConstant] = XsConstant('cVietnamese', 31, 'int')
    BULGARIANS: Final[XsConstant] = XsConstant('cBulgarians', 32, 'int')
    TATARS: Final[XsConstant] = XsConstant('cTatars', 33, 'int')
    CUMANS: Final[XsConstant] = XsConstant('cCumans', 34, 'int')
    LITHUANIANS: Final[XsConstant] = XsConstant('cLithuanians', 35, 'int')
    BURGUNDIANS: Final[XsConstant] = XsConstant('cBurgundians', 36, 'int')
    SICILIANS: Final[XsConstant] = XsConstant('cSicilians', 37, 'int')
    POLES: Final[XsConstant] = XsConstant('cPoles', 38, 'int')
    BOHEMIANS: Final[XsConstant] = XsConstant('cBohemians', 39, 'int')
    DRAVIDIANS: Final[XsConstant] = XsConstant('cDravidians', 40, 'int')
    BENGALIS: Final[XsConstant] = XsConstant('cBengalis', 41, 'int')
    GURJARAS: Final[XsConstant] = XsConstant('cGurjaras', 42, 'int')
    ROMANS: Final[XsConstant] = XsConstant('cRomans', 43, 'int')
    ARMENIANS: Final[XsConstant] = XsConstant('cArmenians', 44, 'int')
    GEORGIANS: Final[XsConstant] = XsConstant('cGeorgians', 45, 'int')
    ACHAEMENIDS: Final[XsConstant] = XsConstant('cAchaemenids', 46, 'int')
    ATHENIANS: Final[XsConstant] = XsConstant('cAthenians', 47, 'int')
    SPARTANS: Final[XsConstant] = XsConstant('cSpartans', 48, 'int')
    SHU: Final[XsConstant] = XsConstant('cShu', 49, 'int')
    WU: Final[XsConstant] = XsConstant('cWu', 50, 'int')
    WEI: Final[XsConstant] = XsConstant('cWei', 51, 'int')
    JURCHENS: Final[XsConstant] = XsConstant('cJurchens', 52, 'int')
    KHITANS: Final[XsConstant] = XsConstant('cKhitans', 53, 'int')
    MACEDONIANS: Final[XsConstant] = XsConstant('cMacedonians', 54, 'int')
    THRACIANS: Final[XsConstant] = XsConstant('cThracians', 55, 'int')
    PURU: Final[XsConstant] = XsConstant('cPuru', 56, 'int')
    MUISCA: Final[XsConstant] = XsConstant('cMuisca', 57, 'int')
    MAPUCHE: Final[XsConstant] = XsConstant('cMapuche', 58, 'int')
    TUPI: Final[XsConstant] = XsConstant('cTupi', 59, 'int')
    NUM_CIVS: Final[XsConstant] = XsConstant('cNumCivs', 60, 'int')
    AOE_EGYPTIANS: Final[XsConstant] = XsConstant('cAoeEgyptians', 1, 'int')
    AOE_GREEKS: Final[XsConstant] = XsConstant('cAoeGreeks', 2, 'int')
    AOE_BABYLONIANS: Final[XsConstant] = XsConstant('cAoeBabylonians', 3, 'int')
    AOE_ASSYRIANS: Final[XsConstant] = XsConstant('cAoeAssyrians', 4, 'int')
    AOE_MINOANS: Final[XsConstant] = XsConstant('cAoeMinoans', 5, 'int')
    AOE_HITTITES: Final[XsConstant] = XsConstant('cAoeHittites', 6, 'int')
    AOE_PHOENICIANS: Final[XsConstant] = XsConstant('cAoePhoenicians', 7, 'int')
    AOE_SUMERIANS: Final[XsConstant] = XsConstant('cAoeSumerians', 8, 'int')
    AOE_PERSIANS: Final[XsConstant] = XsConstant('cAoePersians', 9, 'int')
    AOE_SHANG: Final[XsConstant] = XsConstant('cAoeShang', 10, 'int')
    AOE_YAMATO: Final[XsConstant] = XsConstant('cAoeYamato', 11, 'int')
    AOE_CHOSON: Final[XsConstant] = XsConstant('cAoeChoson', 12, 'int')
    AOE_ROMANS: Final[XsConstant] = XsConstant('cAoeRomans', 13, 'int')
    AOE_CARTHAGINIANS: Final[XsConstant] = XsConstant('cAoeCarthaginians', 14, 'int')
    AOE_PALMYRANS: Final[XsConstant] = XsConstant('cAoePalmyrans', 15, 'int')
    AOE_MACEDONIANS: Final[XsConstant] = XsConstant('cAoeMacedonians', 16, 'int')
    AOE_LAC_VIET: Final[XsConstant] = XsConstant('cAoeLacViet', 17, 'int')
    NUM_AOE_CIVS: Final[XsConstant] = XsConstant('cNumAoeCivs', 18, 'int')


class XsConstantObjectClass:
    """Constants.xs category: Object Classes."""

    ARCHER_CLASS: Final[XsConstant] = XsConstant('cArcherClass', 900, 'int')
    ARTIFACT_CLASS: Final[XsConstant] = XsConstant('cArtifactClass', 901, 'int')
    TRADE_BOAT_CLASS: Final[XsConstant] = XsConstant('cTradeBoatClass', 902, 'int')
    BUILDING_CLASS: Final[XsConstant] = XsConstant('cBuildingClass', 903, 'int')
    VILLAGER_CLASS: Final[XsConstant] = XsConstant('cVillagerClass', 904, 'int')
    SEA_FISH_CLASS: Final[XsConstant] = XsConstant('cSeaFishClass', 905, 'int')
    INFANTRY_CLASS: Final[XsConstant] = XsConstant('cInfantryClass', 906, 'int')
    FORAGE_BUSH_CLASS: Final[XsConstant] = XsConstant('cForageBushClass', 907, 'int')
    STONE_MINE_CLASS: Final[XsConstant] = XsConstant('cStoneMineClass', 908, 'int')
    PREY_ANIMAL_CLASS: Final[XsConstant] = XsConstant('cPreyAnimalClass', 909, 'int')
    PREDATOR_ANIMAL_CLASS: Final[XsConstant] = XsConstant('cPredatorAnimalClass', 910, 'int')
    MISCELLANEOUS_CLASS: Final[XsConstant] = XsConstant('cMiscellaneousClass', 911, 'int')
    CAVALRY_CLASS: Final[XsConstant] = XsConstant('cCavalryClass', 912, 'int')
    SIEGE_WEAPON_CLASS: Final[XsConstant] = XsConstant('cSiegeWeaponClass', 913, 'int')
    TERRAIN_CLASS: Final[XsConstant] = XsConstant('cTerrainClass', 914, 'int')
    TREE_CLASS: Final[XsConstant] = XsConstant('cTreeClass', 915, 'int')
    TREE_STUMP_CLASS: Final[XsConstant] = XsConstant('cTreeStumpClass', 916, 'int')
    HEALER_CLASS: Final[XsConstant] = XsConstant('cHealerClass', 917, 'int')
    MONK_CLASS: Final[XsConstant] = XsConstant('cMonkClass', 918, 'int')
    TRADE_CART_CLASS: Final[XsConstant] = XsConstant('cTradeCartClass', 919, 'int')
    TRANSPORT_SHIP_CLASS: Final[XsConstant] = XsConstant('cTransportShipClass', 920, 'int')
    FISHING_BOAT_CLASS: Final[XsConstant] = XsConstant('cFishingBoatClass', 921, 'int')
    WARSHIP_CLASS: Final[XsConstant] = XsConstant('cWarshipClass', 922, 'int')
    CONQUISTADOR_CLASS: Final[XsConstant] = XsConstant('cConquistadorClass', 923, 'int')
    WAR_ELEPHANT_CLASS: Final[XsConstant] = XsConstant('cWarElephantClass', 924, 'int')
    HERO_CLASS: Final[XsConstant] = XsConstant('cHeroClass', 925, 'int')
    ELEPHANT_ARCHER_CLASS: Final[XsConstant] = XsConstant('cElephantArcherClass', 926, 'int')
    WALL_CLASS: Final[XsConstant] = XsConstant('cWallClass', 927, 'int')
    PHALANX_CLASS: Final[XsConstant] = XsConstant('cPhalanxClass', 928, 'int')
    DOMESTIC_ANIMAL_CLASS: Final[XsConstant] = XsConstant('cDomesticAnimalClass', 929, 'int')
    FLAG_CLASS: Final[XsConstant] = XsConstant('cFlagClass', 930, 'int')
    DEEP_SEA_FISH_CLASS: Final[XsConstant] = XsConstant('cDeepSeaFishClass', 931, 'int')
    GOLD_MINE: Final[XsConstant] = XsConstant('cGoldMine', 932, 'int')
    SHORE_FISH: Final[XsConstant] = XsConstant('cShoreFish', 933, 'int')
    CLIFF_CLASS: Final[XsConstant] = XsConstant('cCliffClass', 934, 'int')
    PETARD_CLASS: Final[XsConstant] = XsConstant('cPetardClass', 935, 'int')
    CAVALRY_ARCHER_CLASS: Final[XsConstant] = XsConstant('cCavalryArcherClass', 936, 'int')
    DOPPELGANGER_CLASS: Final[XsConstant] = XsConstant('cDoppelgangerClass', 937, 'int')
    BIRD_CLASS: Final[XsConstant] = XsConstant('cBirdClass', 938, 'int')
    GATE_CLASS: Final[XsConstant] = XsConstant('cGateClass', 939, 'int')
    SALVAGE_PILE_CLASS: Final[XsConstant] = XsConstant('cSalvagePileClass', 940, 'int')
    RESOURCE_PILE_CLASS: Final[XsConstant] = XsConstant('cResourcePileClass', 941, 'int')
    RELIC_CLASS: Final[XsConstant] = XsConstant('cRelicClass', 942, 'int')
    MONK_WITH_RELIC_CLASS: Final[XsConstant] = XsConstant('cMonkWithRelicClass', 943, 'int')
    HAND_CANNONEER_CLASS: Final[XsConstant] = XsConstant('cHandCannoneerClass', 944, 'int')
    TWO_HANDED_SWORDSMAN_CLASS: Final[XsConstant] = XsConstant('cTwoHandedSwordsmanClass', 945, 'int')
    PIKEMAN_CLASS: Final[XsConstant] = XsConstant('cPikemanClass', 946, 'int')
    SCOUT_CAVALRY_CLASS: Final[XsConstant] = XsConstant('cScoutCavalryClass', 947, 'int')
    ORE_MINE_CLASS: Final[XsConstant] = XsConstant('cOreMineClass', 948, 'int')
    FARM_CLASS: Final[XsConstant] = XsConstant('cFarmClass', 949, 'int')
    SPEARMAN_CLASS: Final[XsConstant] = XsConstant('cSpearmanClass', 950, 'int')
    PACKED_UNIT_CLASS: Final[XsConstant] = XsConstant('cPackedUnitClass', 951, 'int')
    TOWER_CLASS: Final[XsConstant] = XsConstant('cTowerClass', 952, 'int')
    BOARDING_SHIP_CLASS: Final[XsConstant] = XsConstant('cBoardingShipClass', 953, 'int')
    UNPACKED_SIEGE_UNIT_CLASS: Final[XsConstant] = XsConstant('cUnpackedSiegeUnitClass', 954, 'int')
    SCORPION_CLASS: Final[XsConstant] = XsConstant('cScorpionClass', 955, 'int')
    RAIDER_CLASS: Final[XsConstant] = XsConstant('cRaiderClass', 956, 'int')
    CAVALRY_RAIDER_CLASS: Final[XsConstant] = XsConstant('cCavalryRaiderClass', 957, 'int')
    LIVESTOCK_CLASS: Final[XsConstant] = XsConstant('cLivestockClass', 958, 'int')
    KING_CLASS: Final[XsConstant] = XsConstant('cKingClass', 959, 'int')
    MISC_BUILDING_CLASS: Final[XsConstant] = XsConstant('cMiscBuildingClass', 960, 'int')
    CONTROLLED_ANIMAL_CLASS: Final[XsConstant] = XsConstant('cControlledAnimalClass', 961, 'int')
    GOLD_FISH_CLASS: Final[XsConstant] = XsConstant('cGoldFishClass', 963, 'int')
    LAND_MINE_CLASS: Final[XsConstant] = XsConstant('cLandMineClass', 964, 'int')
    SENTINEL_END_CLASS: Final[XsConstant] = XsConstant('cSentinelEndClass', 965, 'int')


class XsConstantReadWriteOffset:
    """Constants.xs category: XS Read/Write Constants."""

    STRING: Final[XsConstant] = XsConstant('cOffsetString', 0, 'int')
    INTEGER: Final[XsConstant] = XsConstant('cOffsetInteger', 1, 'int')
    FLOAT: Final[XsConstant] = XsConstant('cOffsetFloat', 2, 'int')
    VECTOR: Final[XsConstant] = XsConstant('cOffsetVector', 3, 'int')


class XsConstantVictoryCondition:
    """Constants.xs category: Victory Condition Types."""

    STANDARD_VICTORY: Final[XsConstant] = XsConstant('cStandardVictory', 100, 'int')
    WONDER_VICTORY: Final[XsConstant] = XsConstant('cWonderVictory', 101, 'int')
    RELIC_VICTORY: Final[XsConstant] = XsConstant('cRelicVictory', 102, 'int')
    KING_OF_THE_HILL_VICTORY: Final[XsConstant] = XsConstant('cKingOfTheHillVictory', 103, 'int')


class XsConstantDamageClass:
    """Constants.xs category: Damage Classes."""

    INFANTRY: Final[XsConstant] = XsConstant('cDamageClassInfantry', 1, 'int')
    CAPITAL_SHIPS: Final[XsConstant] = XsConstant('cDamageClassCapitalShips', 2, 'int')
    PIERCE: Final[XsConstant] = XsConstant('cDamageClassPierce', 3, 'int')
    MELEE: Final[XsConstant] = XsConstant('cDamageClassMelee', 4, 'int')
    ELEPHANT_UNITS: Final[XsConstant] = XsConstant('cDamageClassElephantUnits', 5, 'int')
    CAVALRY: Final[XsConstant] = XsConstant('cDamageClassCavalry', 8, 'int')
    ALL_BUILDINGS: Final[XsConstant] = XsConstant('cDamageClassAllBuildings', 11, 'int')
    STONE_DEFENSE: Final[XsConstant] = XsConstant('cDamageClassStoneDefense', 13, 'int')
    PREDATOR_ANIMALS: Final[XsConstant] = XsConstant('cDamageClassPredatorAnimals', 14, 'int')
    ARCHERS: Final[XsConstant] = XsConstant('cDamageClassArchers', 15, 'int')
    SHIPS: Final[XsConstant] = XsConstant('cDamageClassShips', 16, 'int')
    RAMS: Final[XsConstant] = XsConstant('cDamageClassRams', 17, 'int')
    TREES: Final[XsConstant] = XsConstant('cDamageClassTrees', 18, 'int')
    UNIQUE_UNITS: Final[XsConstant] = XsConstant('cDamageClassUniqueUnits', 19, 'int')
    SIEGE_WEAPONS: Final[XsConstant] = XsConstant('cDamageClassSiegeWeapons', 20, 'int')
    STANDARD_BUILDINGS: Final[XsConstant] = XsConstant('cDamageClassStandardBuildings', 21, 'int')
    WALLS_AND_GATES: Final[XsConstant] = XsConstant('cDamageClassWallsAndGates', 22, 'int')
    GUNPOWDER_UNITS: Final[XsConstant] = XsConstant('cDamageClassGunpowderUnits', 23, 'int')
    BOARS: Final[XsConstant] = XsConstant('cDamageClassBoars', 24, 'int')
    MONKS: Final[XsConstant] = XsConstant('cDamageClassMonks', 25, 'int')
    CASTLES: Final[XsConstant] = XsConstant('cDamageClassCastles', 26, 'int')
    SPEARMEN: Final[XsConstant] = XsConstant('cDamageClassSpearmen', 27, 'int')
    CAVALRY_ARCHERS: Final[XsConstant] = XsConstant('cDamageClassCavalryArchers', 28, 'int')
    SHOCK_INFANTRY: Final[XsConstant] = XsConstant('cDamageClassShockInfantry', 29, 'int')
    CAMEL_UNITS: Final[XsConstant] = XsConstant('cDamageClassCamelUnits', 30, 'int')
    CONDOTTIERI: Final[XsConstant] = XsConstant('cDamageClassCondottieri', 32, 'int')
    FISHING_SHIPS: Final[XsConstant] = XsConstant('cDamageClassFishingShips', 34, 'int')
    MAMELUKES: Final[XsConstant] = XsConstant('cDamageClassMamelukes', 35, 'int')
    HEROES_AND_KINGS: Final[XsConstant] = XsConstant('cDamageClassHeroesAndKings', 36, 'int')
    HEAVY_SIEGE: Final[XsConstant] = XsConstant('cDamageClassHeavySiege', 37, 'int')
    SKIRMISHERS: Final[XsConstant] = XsConstant('cDamageClassSkirmishers', 38, 'int')
    ROYAL_HEIRS: Final[XsConstant] = XsConstant('cDamageClassRoyalHeirs', 39, 'int')
    NUM_DAMAGE_CLASSES: Final[XsConstant] = XsConstant('cNumDamageClasses', 39, 'int')


class XsConstantTaskAttribute:
    """Constants.xs category: xsTaskAmount Constants."""

    WORK_VALUE_1: Final[XsConstant] = XsConstant('cTaskAttrWorkValue1', 0, 'int')
    WORK_VALUE_2: Final[XsConstant] = XsConstant('cTaskAttrWorkValue2', 1, 'int')
    WORK_RANGE: Final[XsConstant] = XsConstant('cTaskAttrWorkRange', 2, 'int')
    WORK_FLAG_2: Final[XsConstant] = XsConstant('cTaskAttrWorkFlag2', 3, 'int')
    SEARCH_WAIT_TIME: Final[XsConstant] = XsConstant('cTaskAttrSearchWaitTime', 4, 'int')
    COMBAT_LEVEL_FLAG: Final[XsConstant] = XsConstant('cTaskAttrCombatLevelFlag', 5, 'int')
    OWNER_TYPE: Final[XsConstant] = XsConstant('cTaskAttrOwnerType', 6, 'int')
    TERRAIN: Final[XsConstant] = XsConstant('cTaskAttrTerrain', 7, 'int')
    RESOURCE_IN: Final[XsConstant] = XsConstant('cTaskAttrResourceIn', 8, 'int')
    PRODUCTIVITY_RESOURCE: Final[XsConstant] = XsConstant('cTaskAttrProductivityResource', 9, 'int')
    RESOURCE_OUT: Final[XsConstant] = XsConstant('cTaskAttrResourceOut', 10, 'int')
    UNUSED_RESOURCE: Final[XsConstant] = XsConstant('cTaskAttrUnusedResource', 11, 'int')
    MOVING_GRAPHIC: Final[XsConstant] = XsConstant('cTaskAttrMovingGraphic', 12, 'int')
    PROCEEDING_GRAPHIC: Final[XsConstant] = XsConstant('cTaskAttrProceedingGraphic', 13, 'int')
    WORKING_GRAPHIC: Final[XsConstant] = XsConstant('cTaskAttrWorkingGraphic', 14, 'int')
    CARRYING_GRAPHIC: Final[XsConstant] = XsConstant('cTaskAttrCarryingGraphic', 15, 'int')
    GATHERING_SOUND: Final[XsConstant] = XsConstant('cTaskAttrGatheringSound', 16, 'int')
    GATHERING_SOUND_EVENT: Final[XsConstant] = XsConstant('cTaskAttrGatheringSoundEvent', 17, 'int')
    GATHERING_SOUND_INT_32: Final[XsConstant] = XsConstant('cTaskAttrGatheringSoundInt32', 18, 'int')
    DEPOSIT_SOUND: Final[XsConstant] = XsConstant('cTaskAttrDepositSound', 19, 'int')
    DEPOSIT_SOUND_EVENT: Final[XsConstant] = XsConstant('cTaskAttrDepositSoundEvent', 20, 'int')
    DEPOSIT_SOUND_INT_32: Final[XsConstant] = XsConstant('cTaskAttrDepositSoundInt32', 21, 'int')
    AUTO_SEARCH: Final[XsConstant] = XsConstant('cTaskAttrAutoSearch', 22, 'int')
    CARRY_CHECK: Final[XsConstant] = XsConstant('cTaskAttrCarryCheck', 23, 'int')
    BUILDING_PICK: Final[XsConstant] = XsConstant('cTaskAttrBuildingPick', 24, 'int')
    GATHER_TYPE: Final[XsConstant] = XsConstant('cTaskAttrGatherType', 25, 'int')
    ENABLE_TARGETING: Final[XsConstant] = XsConstant('cTaskAttrEnableTargeting', 26, 'int')
    ENABLED: Final[XsConstant] = XsConstant('cTaskAttrEnabled', 27, 'int')
    TASK_TYPE: Final[XsConstant] = XsConstant('cTaskAttrTaskType', 28, 'int')
    OBJECT_ID: Final[XsConstant] = XsConstant('cTaskAttrObjectId', 29, 'int')
    OBJECT_CLASS: Final[XsConstant] = XsConstant('cTaskAttrObjectClass', 30, 'int')
    NUM_TASK_ATTRS: Final[XsConstant] = XsConstant('cNumTaskAttrs', 31, 'int')


class XsConstantTaskType:
    """Constants.xs category: xsTask Constants."""

    MOVE_TO: Final[XsConstant] = XsConstant('cTaskTypeMoveTo', 1, 'int')
    FOLLOW: Final[XsConstant] = XsConstant('cTaskTypeFollow', 2, 'int')
    GARRISON: Final[XsConstant] = XsConstant('cTaskTypeGarrison', 3, 'int')
    EXPLORE: Final[XsConstant] = XsConstant('cTaskTypeExplore', 4, 'int')
    GATHER_REBUILD: Final[XsConstant] = XsConstant('cTaskTypeGatherRebuild', 5, 'int')
    GRAZE: Final[XsConstant] = XsConstant('cTaskTypeGraze', 6, 'int')
    COMBAT: Final[XsConstant] = XsConstant('cTaskTypeCombat', 7, 'int')
    SHOOT: Final[XsConstant] = XsConstant('cTaskTypeShoot', 8, 'int')
    ATTACK: Final[XsConstant] = XsConstant('cTaskTypeAttack', 9, 'int')
    FLY: Final[XsConstant] = XsConstant('cTaskTypeFly', 10, 'int')
    UNLOAD_BOAT_LIKE: Final[XsConstant] = XsConstant('cTaskTypeUnloadBoatLike', 12, 'int')
    GUARD: Final[XsConstant] = XsConstant('cTaskTypeGuard', 13, 'int')
    UNLOAD_OVER_WALL: Final[XsConstant] = XsConstant('cTaskTypeUnloadOverWall', 14, 'int')
    MAKE: Final[XsConstant] = XsConstant('cTaskTypeMake', 21, 'int')
    BUILD: Final[XsConstant] = XsConstant('cTaskTypeBuild', 101, 'int')
    MAKE_UNIT: Final[XsConstant] = XsConstant('cTaskTypeMakeUnit', 102, 'int')
    MAKE_TECH: Final[XsConstant] = XsConstant('cTaskTypeMakeTech', 103, 'int')
    CONVERT: Final[XsConstant] = XsConstant('cTaskTypeConvert', 104, 'int')
    HEAL: Final[XsConstant] = XsConstant('cTaskTypeHeal', 105, 'int')
    REPAIR: Final[XsConstant] = XsConstant('cTaskTypeRepair', 106, 'int')
    GET_AUTO_CONVERTED: Final[XsConstant] = XsConstant('cTaskTypeGetAutoConverted', 107, 'int')
    DISCOVERY_ARTIFACT: Final[XsConstant] = XsConstant('cTaskTypeDiscoveryArtifact', 108, 'int')
    HUNT: Final[XsConstant] = XsConstant('cTaskTypeHunt', 110, 'int')
    TRADE: Final[XsConstant] = XsConstant('cTaskTypeTrade', 111, 'int')
    GENERATE_WONDER_VICTORY: Final[XsConstant] = XsConstant('cTaskTypeGenerateWonderVictory', 120, 'int')
    DESELECT_WHEN_TASKED: Final[XsConstant] = XsConstant('cTaskTypeDeselectWhenTasked', 121, 'int')
    LOOT_GATHER: Final[XsConstant] = XsConstant('cTaskTypeLootGather', 122, 'int')
    HOUSING: Final[XsConstant] = XsConstant('cTaskTypeHousing', 123, 'int')
    PACK: Final[XsConstant] = XsConstant('cTaskTypePack', 124, 'int')
    UNPACK_AND_ATTACK: Final[XsConstant] = XsConstant('cTaskTypeUnpackAndAttack', 125, 'int')
    OFF_MAP_TRADE: Final[XsConstant] = XsConstant('cTaskTypeOffMapTrade', 131, 'int')
    PICKUP_UNIT: Final[XsConstant] = XsConstant('cTaskTypePickupUnit', 132, 'int')
    CHARGE_ATTACK: Final[XsConstant] = XsConstant('cTaskTypeChargeAttack', 133, 'int')
    TRANSFORM_UNIT: Final[XsConstant] = XsConstant('cTaskTypeTransformUnit', 134, 'int')
    KIDNAP_UNIT: Final[XsConstant] = XsConstant('cTaskTypeKidnapUnit', 135, 'int')
    DEPOSIT_UNIT: Final[XsConstant] = XsConstant('cTaskTypeDepositUnit', 136, 'int')
    SHEAR: Final[XsConstant] = XsConstant('cTaskTypeShear', 149, 'int')
    GENERATE_RESOURCES: Final[XsConstant] = XsConstant('cTaskTypeGenerateResources', 151, 'int')
    MOVEMENT_DAMAGE: Final[XsConstant] = XsConstant('cTaskTypeMovementDamage', 152, 'int')
    MOVABLE_DROPSITE: Final[XsConstant] = XsConstant('cTaskTypeMovableDropsite', 153, 'int')
    LOOT: Final[XsConstant] = XsConstant('cTaskTypeLoot', 154, 'int')
    AURA: Final[XsConstant] = XsConstant('cTaskTypeAura', 155, 'int')
    EXTRA_SPAWN: Final[XsConstant] = XsConstant('cTaskTypeExtraSpawn', 156, 'int')
    STINGER: Final[XsConstant] = XsConstant('cTaskTypeStinger', 157, 'int')
    HP_TRANSFORM: Final[XsConstant] = XsConstant('cTaskTypeHPTransform', 158, 'int')
    AMPHIBIOUS: Final[XsConstant] = XsConstant('cTaskTypeAmphibious', 159, 'int')
    HP_MODIFIER: Final[XsConstant] = XsConstant('cTaskTypeHPModifier', 160, 'int')
    REFUND: Final[XsConstant] = XsConstant('cTaskTypeRefund', 161, 'int')


class XsConstantTechState:
    """Constants.xs category: xsTechState Constants."""

    NOT_READY: Final[XsConstant] = XsConstant('cTechStateNotReady', 0, 'int')
    READY: Final[XsConstant] = XsConstant('cTechStateReady', 1, 'int')
    QUEUED: Final[XsConstant] = XsConstant('cTechStateQueued', 4, 'int')
    RESEARCHING: Final[XsConstant] = XsConstant('cTechStateResearching', 2, 'int')
    DONE: Final[XsConstant] = XsConstant('cTechStateDone', 3, 'int')
    DISABLED: Final[XsConstant] = XsConstant('cTechStateDisabled', -1, 'int')
    INVALID: Final[XsConstant] = XsConstant('cTechStateInvalid', -2, 'int')


class XsConstantObjectType:
    """Constants.xs category: Object Type Constants."""

    EYE_CANDY: Final[XsConstant] = XsConstant('cObjectTypeEyeCandy', 10, 'int')
    TREES: Final[XsConstant] = XsConstant('cObjectTypeTrees', 15, 'int')
    ANIMATED: Final[XsConstant] = XsConstant('cObjectTypeAnimated', 20, 'int')
    DOPPLEGANGER: Final[XsConstant] = XsConstant('cObjectTypeDoppleganger', 25, 'int')
    MOVING: Final[XsConstant] = XsConstant('cObjectTypeMoving', 30, 'int')
    ACTING: Final[XsConstant] = XsConstant('cObjectTypeActing', 40, 'int')
    COMBAT: Final[XsConstant] = XsConstant('cObjectTypeCombat', 50, 'int')
    PROJECTILE: Final[XsConstant] = XsConstant('cObjectTypeProjectile', 60, 'int')
    CREATABLE: Final[XsConstant] = XsConstant('cObjectTypeCreatable', 70, 'int')
    BUILDING: Final[XsConstant] = XsConstant('cObjectTypeBuilding', 80, 'int')
    LEGACY_TREE: Final[XsConstant] = XsConstant('cObjectTypeLegacyTree', 90, 'int')


class XsConstantPlayerType:
    """Constants.xs category: Player Type Constants."""

    NONE: Final[XsConstant] = XsConstant('cPlayerTypeNone', -1, 'int')
    SCENARIO_EDITOR_PHANTOM: Final[XsConstant] = XsConstant('cPlayerTypeScenarioEditorPhantom', 0, 'int')
    HUMAN: Final[XsConstant] = XsConstant('cPlayerTypeHuman', 1, 'int')
    GAIA: Final[XsConstant] = XsConstant('cPlayerTypeGaia', 2, 'int')
    COMPUTER: Final[XsConstant] = XsConstant('cPlayerTypeComputer', 3, 'int')


class XsConstantDiplomacy:
    """Constants.xs category: Diplomacy Constants."""

    INVALID: Final[XsConstant] = XsConstant('cDiplomacyInvalid', -1, 'int')
    ALLY: Final[XsConstant] = XsConstant('cDiplomacyAlly', 0, 'int')
    NEUTRAL: Final[XsConstant] = XsConstant('cDiplomacyNeutral', 1, 'int')
    ANY: Final[XsConstant] = XsConstant('cDiplomacyAny', 2, 'int')
    ENEMY: Final[XsConstant] = XsConstant('cDiplomacyEnemy', 3, 'int')
    TREATY: Final[XsConstant] = XsConstant('cDiplomacyTreaty', 4, 'int')


class XsConstantColorMood:
    """Constants.xs category: Color Mood Constants."""

    DEFAULT: Final[XsConstant] = XsConstant('cColorMoodDefault', 0, 'int')
    AUTUMN: Final[XsConstant] = XsConstant('cColorMoodAutumn', 1, 'int')
    WINTER: Final[XsConstant] = XsConstant('cColorMoodWinter', 2, 'int')
    JUNGLE: Final[XsConstant] = XsConstant('cColorMoodJungle', 3, 'int')
    DESERT: Final[XsConstant] = XsConstant('cColorMoodDesert', 4, 'int')
    NIGHT: Final[XsConstant] = XsConstant('cColorMoodNight', 5, 'int')
    EVENING: Final[XsConstant] = XsConstant('cColorMoodEvening', 6, 'int')
    SPRING: Final[XsConstant] = XsConstant('cColorMoodSpring', 7, 'int')
    SAVANNAH: Final[XsConstant] = XsConstant('cColorMoodSavannah', 8, 'int')
    ARCTIC: Final[XsConstant] = XsConstant('cColorMoodArctic', 9, 'int')
    RAINFOREST: Final[XsConstant] = XsConstant('cColorMoodRainforest', 10, 'int')
    SWAMP: Final[XsConstant] = XsConstant('cColorMoodSwamp', 11, 'int')
    STEPPES: Final[XsConstant] = XsConstant('cColorMoodSteppes', 12, 'int')
    MISTY: Final[XsConstant] = XsConstant('cColorMoodMisty', 13, 'int')
    SUMMER: Final[XsConstant] = XsConstant('cColorMoodSummer', 14, 'int')
    MURKY: Final[XsConstant] = XsConstant('cColorMoodMurky', 15, 'int')
    BRUMOUS: Final[XsConstant] = XsConstant('cColorMoodBrumous', 16, 'int')
    TWILIGHT: Final[XsConstant] = XsConstant('cColorMoodTwilight', 17, 'int')
    DARKNESS: Final[XsConstant] = XsConstant('cColorMoodDarkness', 18, 'int')
    NUM_COLOR_MOODS: Final[XsConstant] = XsConstant('cNumColorMoods', 19, 'int')


class XsConstantDifficulty:
    """Constants.xs category: Difficulty Constants."""

    EXTREME: Final[XsConstant] = XsConstant('cDifficultyExtreme', -1, 'int')
    HARDEST: Final[XsConstant] = XsConstant('cDifficultyHardest', 0, 'int')
    HARD: Final[XsConstant] = XsConstant('cDifficultyHard', 1, 'int')
    MODERATE: Final[XsConstant] = XsConstant('cDifficultyModerate', 2, 'int')
    EASY: Final[XsConstant] = XsConstant('cDifficultyEasy', 3, 'int')
    EASIEST: Final[XsConstant] = XsConstant('cDifficultyEasiest', 4, 'int')


class XsConstantPanelPosition:
    """Constants.xs category: Panel Position Constants."""

    TOP: Final[XsConstant] = XsConstant('cPanelTop', 0, 'int')
    MIDDLE: Final[XsConstant] = XsConstant('cPanelMiddle', 1, 'int')
    BOTTOM: Final[XsConstant] = XsConstant('cPanelBottom', 2, 'int')


class XsConstantLanguage:
    """Constants.xs category: Language Constants."""

    PORTUGESE: Final[XsConstant] = XsConstant('cLocalePortugese', 0, 'int')
    GERMAN: Final[XsConstant] = XsConstant('cLocaleGerman', 1, 'int')
    ENGLISH: Final[XsConstant] = XsConstant('cLocaleEnglish', 2, 'int')
    SPANISH: Final[XsConstant] = XsConstant('cLocaleSpanish', 3, 'int')
    FRENCH: Final[XsConstant] = XsConstant('cLocaleFrench', 4, 'int')
    HINDI: Final[XsConstant] = XsConstant('cLocaleHindi', 5, 'int')
    ITALIAN: Final[XsConstant] = XsConstant('cLocaleItalian', 6, 'int')
    JAPANESE: Final[XsConstant] = XsConstant('cLocaleJapanese', 7, 'int')
    KOREAN: Final[XsConstant] = XsConstant('cLocaleKorean', 8, 'int')
    MALAY: Final[XsConstant] = XsConstant('cLocaleMalay', 9, 'int')
    SPANISH_LATIN_AMERICAN: Final[XsConstant] = XsConstant('cLocaleSpanishLatinAmerican', 10, 'int')
    RUSSIAN: Final[XsConstant] = XsConstant('cLocaleRussian', 11, 'int')
    TURKISH: Final[XsConstant] = XsConstant('cLocaleTurkish', 12, 'int')
    CHINESE_TRADITIONAL: Final[XsConstant] = XsConstant('cLocaleChineseTraditional', 13, 'int')
    VIETNAMESE: Final[XsConstant] = XsConstant('cLocaleVietnamese', 14, 'int')
    CHINESE_SIMPLIFIED: Final[XsConstant] = XsConstant('cLocaleChineseSimplified', 15, 'int')
    POLISH: Final[XsConstant] = XsConstant('cLocalePolish', 16, 'int')
    NUM_LOCALES: Final[XsConstant] = XsConstant('cNumLocales', 17, 'int')


class XsConstantTimerUnit:
    """Constants.xs category: Timer Constants."""

    YEARS: Final[XsConstant] = XsConstant('cTimerUnitYears', 0, 'int')
    MINUTES: Final[XsConstant] = XsConstant('cTimerUnitMinutes', 1, 'int')
    SECONDS: Final[XsConstant] = XsConstant('cTimerUnitSeconds', 2, 'int')
    MINUTES_AND_SECONDS: Final[XsConstant] = XsConstant('cTimerUnitMinutesAndSeconds', 3, 'int')


class XsConstantColor:
    """Constants.xs category: Color Constants."""

    BLUE: Final[XsConstant] = XsConstant('cColorBlue', '<BLUE>', 'string')
    RED: Final[XsConstant] = XsConstant('cColorRed', '<RED>', 'string')
    GREEN: Final[XsConstant] = XsConstant('cColorGreen', '<GREEN>', 'string')
    YELLOW: Final[XsConstant] = XsConstant('cColorYellow', '<YELLOW>', 'string')
    AQUA: Final[XsConstant] = XsConstant('cColorAqua', '<AQUA>', 'string')
    PURPLE: Final[XsConstant] = XsConstant('cColorPurple', '<PURPLE>', 'string')
    GRAY: Final[XsConstant] = XsConstant('cColorGray', '<GRAY>', 'string')
    ORANGE: Final[XsConstant] = XsConstant('cColorOrange', '<ORANGE>', 'string')
    WHITE: Final[XsConstant] = XsConstant('cColorWhite', '<WHITE>', 'string')
    BLACK: Final[XsConstant] = XsConstant('cColorBlack', '<BLACK>', 'string')


class XsConstantTechAttribute:
    """Constants.xs category: Tech Attribute Constants."""

    STATE: Final[XsConstant] = XsConstant('cTechState', 0, 'int')
    COST: Final[XsConstant] = XsConstant('cTechCost', 1, 'int')
    RESEARCH_TIME: Final[XsConstant] = XsConstant('cTechResearchTime', 2, 'int')
    RESEARCH_LOCATION: Final[XsConstant] = XsConstant('cTechResearchLocation', 3, 'int')
    BUTTON_LOCATION: Final[XsConstant] = XsConstant('cTechButtonLocation', 4, 'int')
    HOTKEY_ID: Final[XsConstant] = XsConstant('cTechHotkeyId', 5, 'int')
    ICON_ID: Final[XsConstant] = XsConstant('cTechIconId', 6, 'int')
    EFFECT_ID: Final[XsConstant] = XsConstant('cTechEffectId', 7, 'int')
    CURRENT_RESEARCH_LOCATION: Final[XsConstant] = XsConstant('cTechCurrentResearchLocation', 8, 'int')
    TIMES_RESEARCHED: Final[XsConstant] = XsConstant('cTechTimesResearched', 9, 'int')
    TIMES_QUEUED: Final[XsConstant] = XsConstant('cTechTimesQueued', 10, 'int')
    STACKING_ALLOWED: Final[XsConstant] = XsConstant('cTechStackingAllowed', 11, 'int')
    STACKING_ENABLED: Final[XsConstant] = XsConstant('cTechStackingEnabled', 12, 'int')
    STACKING_CAP: Final[XsConstant] = XsConstant('cTechStackingCap', 13, 'int')


__all__ = [
    'XsConstantAttribute',
    'XsConstantPlayerAge',
    'XsConstantEffectAmount',
    'XsConstantCivilization',
    'XsConstantObjectClass',
    'XsConstantReadWriteOffset',
    'XsConstantVictoryCondition',
    'XsConstantDamageClass',
    'XsConstantTaskAttribute',
    'XsConstantTaskType',
    'XsConstantTechState',
    'XsConstantObjectType',
    'XsConstantPlayerType',
    'XsConstantDiplomacy',
    'XsConstantColorMood',
    'XsConstantDifficulty',
    'XsConstantPanelPosition',
    'XsConstantLanguage',
    'XsConstantTimerUnit',
    'XsConstantColor',
    'XsConstantTechAttribute',
    "XsConstant",
    "XsConstantValue",
]
