from enum import Enum


class ClashRoyaleUnits(Enum):
    SPEAR_GOBLINS = "SPEAR_GOBLINS"
    GOBLINS = "GOBLINS"
    KNIGHT = "KNIGHT"
    ARCHERS = "ARCHERS"
    PRINCE = "PRINCE"
    MINI_PEKKA = "MINI_PEKKA"
    MUSKETEER = "MUSKETEER"
    SKELETONS = "SKELETONS"
    GOLEM = "GOLEM"
    ROYAL_HOGS = "ROYAL_HOGS"
    DARK_PRINCE = "DARK_PRINCE"
    WIZARD = "WIZARD"
    PRINCESS = "PRINCESS"
    BARBARIANS = "BARBARIANS"
    BATTLE_RAM = "BATTLE_RAM"
    WITCH = "WITCH"
    DART_GOBLIN = "DART_GOBLIN"
    FIRE_SPIRIT = "FIRE_SPIRIT"
    WALLBREAKERS = "WALLBREAKERS"
    HOG_RIDER = "HOG_RIDER"
    MAGIC_ARCHER = "MAGIC_ARCHER"
    ELITE_BARBARIANS = "ELITE_BARBARIANS"
    ICE_WIZARD = "ICE_WIZARD"
    SKELETON_ARMY = "SKELETON_ARMY"
    GOBLIN_GANG = "GOBLIN_GANG"
    GOBLIN_HUT = "GOBLIN_HUT"
    BOMB_TOWER = "BOMB_TOWER"
    INFERNO_TOWER = "INFERNO_TOWER"
    XBOW = "XBOW"
    MORTAR = "MORTAR"
    ARROWS = "ARROWS"
    THE_LOG = "THE_LOG"
    FIREBALL = "FIREBALL"
    POISON = "POISON"
    FREEZE = "FREEZE"
    RAGE = "RAGE"


class ClashRoyaleVariables(Enum):

    @property
    def ID(self) -> int:
        return self.value[0]

    @property
    def NAME(self) -> str:
        return self.value[1]

    ELIXIR_PLAYER1 = 0, "ELIXIR PLAYER1"
    ELIXIR_PLAYER2 = 1, "ELIXIR PLAYER2"
    DECK_SELECT_PLAYER1 = 2, "DECK_SELECT_PLAYER1_"
    DECK_SELECT_PLAYER2 = 3, "DECK_SELECT_PLAYER2_"
    HOTKEY_SELECT_PLAYER1 = 4, "HOTKEY_SELECT_PLAYER1"
    HOTKEY_SELECT_PLAYER2 = 5, "HOTKEY_SELECT_PLAYER2"
    SPEAR_GOBLINS_P1 = 50, "SPEAR_GOBLINS_P1"
    SPEAR_GOBLINS_P2 = 51, "SPEAR_GOBLINS_P2"
    GOBLINS_P1 = 52, "GOBLINS_P1"
    GOBLINS_P2 = 53, "GOBLINS_P2"
    KNIGHT_P1 = 54, "KNIGHT_P1"
    KNIGHT_P2 = 55, "KNIGHT_P2"
    ARCHERS_P1 = 56, "ARCHERS_P1"
    ARCHERS_P2 = 57, "ARCHERS_P2"
    PRINCE_P1 = 58, "PRINCE_P1"
    PRINCE_P2 = 59, "PRINCE_P2"
    MINI_PEKKA_P1 = 60, "MINI_PEKKA_P1"
    MINI_PEKKA_P2 = 61, "MINI_PEKKA_P2"
    MUSKETEER_P1 = 62, "MUSKETEER_P1"
    MUSKETEER_P2 = 63, "MUSKETEER_P2"
    SKELETONS_P1 = 64, "SKELETONS_P1"
    SKELETONS_P2 = 65, "SKELETONS_P2"
    GOLEM_P1 = 66, "GOLEM_P1"
    GOLEM_P2 = 67, "GOLEM_P2"
    ROYAL_HOGS_P1 = 68, "ROYAL_HOGS_P1"
    ROYAL_HOGS_P2 = 69, "ROYAL_HOGS_P2"
    DARK_PRINCE_P1 = 70, "DARK_PRINCE_P1"
    DARK_PRINCE_P2 = 71, "DARK_PRINCE_P2"
    WIZARD_P1 = 72, "WIZARD_P1"
    WIZARD_P2 = 73, "WIZARD_P2"
    PRINCESS_P1 = 74, "PRINCESS_P1"
    PRINCESS_P2 = 75, "PRINCESS_P2"
    BARBARIANS_P1 = 76, "BARBARIANS_P1"
    BARBARIANS_P2 = 77, "BARBARIANS_P2"
    BATTLE_RAM_P1 = 78, "BATTLE_RAM_P1"
    BATTLE_RAM_P2 = 79, "BATTLE_RAM_P2"
    WITCH_P1 = 80, "WITCH_P1"
    WITCH_P2 = 81, "WITCH_P2"
    DART_GOBLIN_P1 = 82, "DART_GOBLIN_P1"
    DART_GOBLIN_P2 = 83, "DART_GOBLIN_P2"
    FIRE_SPIRIT_P1 = 84, "FIRE_SPIRIT_P1"
    FIRE_SPIRIT_P2 = 85, "FIRE_SPIRIT_P2"
    WALLBREAKERS_P1 = 86, "WALLBREAKERS_P1"
    WALLBREAKERS_P2 = 87, "WALLBREAKERS_P2"
    HOG_RIDER_P1 = 88, "HOG_RIDER_P1"
    HOG_RIDER_P2 = 89, "HOG_RIDER_P2"
    MAGIC_ARCHER_P1 = 90, "MAGIC_ARCHER_P1"
    MAGIC_ARCHER_P2 = 91, "MAGIC_ARCHER_P2"
    ELITE_BARBARIANS_P1 = 92, "ELITE_BARBARIANS_P1"
    ELITE_BARBARIANS_P2 = 93, "ELITE_BARBARIANS_P2"
    ICE_WIZARD_P1 = 94, "ICE_WIZARD_P1"
    ICE_WIZARD_P2 = 95, "ICE_WIZARD_P2"
    SKELETON_ARMY_P1 = 96, "SKELETON_ARMY_P1"
    SKELETON_ARMY_P2 = 97, "SKELETON_ARMY_P2"
    GLOBLIN_GANG_P1 = 98, "GLOBLIN_GANG_P1"
    GLOBLIN_GANG_P2 = 99, "GLOBLIN_GANG_P2"
    GOBLIN_HUT_P1 = 100, "GOBLIN_HUT_P1"
    GOBLIN_HUT_P2 = 101, "GOBLIN_HUT_P2"
    BOMB_TOWER_P1 = 102, "BOMB_TOWER_P1"
    BOMB_TOWER_P2 = 103, "BOMB_TOWER_P2"
    INFERNO_TOWER_P1 = 104, "INFERNO_TOWER_P1"
    INFERNO_TOWER_P2 = 105, "INFERNO_TOWER_P2"
    XBOW_P1 = 106, "XBOW_P1"
    XBOW_P2 = 107, "XBOW_P2"
    MORTAR_P1 = 108, "MORTAR_P1"
    MORTAR_P2 = 109, "MORTAR_P2"
    ARROWS_P1 = 110, "ARROWS_P1"
    ARROWS_P2 = 111, "ARROWS_P2"
    THE_LOG_P1 = 112, "THE_LOG_P1"
    THE_LOG_P2 = 113, "THE_LOG_P2"
    FIREBALL_P1 = 114, "FIREBALL_P1"
    FIREBALL_P2 = 115, "FIREBALL_P2"
    POISON_P1 = 116, "POISON_P1"
    POISON_P2 = 117, "POISON_P2"
    FREEZE_P1 = 118, "FREEZE_P1"
    FREEZE_P2 = 119, "FREEZE_P2"
    RAGE_P1 = 120, "RAGE_P1"
    RAGE_P2 = 121, "RAGE_P2"


class ClashRoyaleSounds:
    ACTIVATE_CENTRAL_TOWER = "clash_activar_torre_central"
    BATTLE_RAM_SPAWN = "clash_ariete"
    BATTLE_RAM_CHARGE = "clash_ariete_carga"
    ARCHERS_SPAWN = "clash_arqueras"
    XBOW_SPAWN = "clash_ballesta"
    BARBARIANS_SPAWN = "clash_barbaros"
    FIREBALL_CAST = "clash_bola_fuego"
    WITCH_SPAWN = "clash_bruja"
    WITCH_SKELETONS = "clash_bruja_esqueletos"
    KNIGHT_SPAWN = "clash_caballero"
    GOBLIN_HUT_SPAWN = "clash_choza_duendes"
    DOUBLE_ELIXIR = "clash_doble_elixir"
    SPEAR_GOBLINS_SPAWN = "clash_duendes_lanza"
    DART_GOBLIN_SPAWN = "clash_duende_lanzadardos"
    PLAYER_WAITING = "clash_esperando_partida"
    FIRE_SPIRIT_SPAWN = "clash_espiritu_fuego"
    SKELETONS_SPAWN = "clash_esqueletos"
    ARROWS_CAST = "clash_flechas"
    GOLEM_SPAWN = "clash_golem"
    MATCH_START = "clash_inicio_partida"
    INTO = "clash_intro"
    PLAYERS_READY = "clash_jugadores_listos"
    WIZARD_SPAWN = "clash_mago"
    MINI_PEKKA_SPAWN = "clash_mini_pekka"
    HOG_RIDER_SPAWN = "clash_montapuercos"
    MUSKETEER_SPAWN = "clash_mosquetera"
    EMOTE_CHICKEN = "clash_pollo"
    PRINCESS_SPAWN = "clash_princesa"
    PRINCE_SPAWN = "clash_principe"
    DARK_PRINCE_SPAWN = "clash_principe_oscuro"
    EMOTE_KING_LAUGH = "clash_risa_rey"
    WALLBREAKERS_SPAWN = "clash_rompemuros"
    CARD_SELECT = "clash_seleccionar_carta"
    BOMB_TOWER_SPAWN = "clash_torre_bombardera"
    ENEMY_TOWER_DESTROYED = "clash_torre_enemiga_destruida"
    INFERNO_TOWER_SPAWN = "clash_torre_infernal"
    OWN_TOWER_DESTROYED = "clash_torre_propia_destruida"
    THE_LOG_CAST = "clash_tronco"
    EXECUTIONER_SPAWN = "clash_verdugo"


class ClashRoyaleHotkeys:
    HOTKEY_DICT = {
        1: 16344,
        2: 16157,
        3: 16464,
        4: 16487,
        5: 16144,
        6: 16149,
        7: 16161,
        8: 16161
    }


class ClashRoyaleStrings:
    SCENARIO_INSTRUCTIONS = 707000
    SCENARIO_HINTS = 707001
    SELECT_INSTRUCTIONS = 707002
    SELECT_FINISHED_P1 = 707013
    SELECT_FINISHED_P2 = 707018
    SELECTED_CARDS_TRIGGER = 707030
    MATCH_STARTS_WARNING = 707019
    MATCH_STARTS = 707020
    DOUBLE_ELIXIR = 707034
    DESCRIPTION_SPEAR_GOBLINS = 707003
    DESCRIPTION_ARCHERS = 707004
    DESCRIPTION_KNIGHT = 707005
    DESCRIPTION_PRINCE = 707006
    DESCRIPTION_GOLEM = 707007
    DESCRIPTION_MUSKETEER = 707008
    DESCRIPTION_MINI_PEKKA = 707009
    DESCRIPTION_FIREBALL = 707010
    DESCRIPTION_SKELETONS = 707011
    DESCRIPTION_XBOW = 707012
    DESCRIPTION_DART_GOBLIN = 707014
    DESCRIPTION_HOG_RIDER = 707015
    DESCRIPTION_BOMB_TOWER = 707016
    DESCRIPTION_INFERNO_TOWER = 707017
    DESCRIPTION_DARK_PRINCE = 707021
    DESCRIPTION_EXECUTIONER = 707022
    DESCRIPTION_PRINCESS = 707023
    DESCRIPTION_WIZARD = 707024
    DESCRIPTION_FIRE_SPIRIT = 707025
    DESCRIPTION_GOBLIN_HUT = 707026
    DESCRIPTION_BATTLE_RAM = 707027
    DESCRIPTION_WALLBREAKERS = 707028
    DESCRIPTION_WITCH = 707029
    DESCRIPTION_BARBARIANS = 707031
    DESCRIPTION_THE_LOG = 707032
    DESCRIPTION_ARROWS = 707033
    NAME_SPEAR_GOBLINS = 707036
    NAME_ARCHERS = 707038
    NAME_KNIGHT = 707039
    NAME_PRINCE = 707041
    NAME_GOLEM = 707043
    NAME_MUSKETEER = 707045
    NAME_MINI_PEKKA = 707046
    NAME_SKELETONS = 707048
    NAME_XBOW = 707050
    NAME_THE_LOG = 707051
    NAME_DART_GOBLIN = 707052
    NAME_BOMB_TOWER = 707053
    NAME_INFERNO_TOWER = 707054
    NAME_GOBLIN_HUT = 707055
    NAME_BARBARIAN = 707056
    NAME_WITCH = 707057
    NAME_WALLBREAKERS = 707058
    NAME_BATTLE_RAM = 707059
    NAME_WIZARD = 707060
    NAME_PRINCESS = 707061
    NAME_EXECUTIONER = 707062
    NAME_DARK_PRINCE = 707063
    NAME_HOG_RIDER = 707064
    NAME_ARROWS = 707065
    NAME_FIREBALL = 707066
    NAME_FIRE_SPIRIT = 707067
    NAME_GOLEMITES = 707068
    ELIXIR_COST_1 = 707047
    ELIXIR_COST_2 = 707035
    ELIXIR_COST_3 = 707037
    ELIXIR_COST_4 = 707044
    ELIXIR_COST_5 = 707040
    ELIXIR_COST_6 = 707049
    ELIXIR_COST_8 = 707042
    PLAYER1 = 707069
    PLAYER2 = 707070
    PLAYER_ARENA = 707071
